/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
void sub_102D0();
// int execlp(const char *file, const char *arg, ...);
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int _gmon_start__(void); weak
// void abort(void);
int __fastcall main(int a1, char **a2, char **a3); // idb
void __noreturn start(void (*a1)(), int a2, int a3, int a4, ...);
int sub_10380();
char *sub_103A4();
__int64 sub_103C8();
char *sub_103F4();
int __fastcall init(int a1, int a2, int a3);
int nullsub_1(); // weak
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN *off_20F10 = (_UNKNOWN *)0x1040D; // weak
_UNKNOWN *off_20F14 = (_UNKNOWN *)0x103F5; // weak
char byte_21028; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (000102C4) --------------------------------------------------------
int init_proc()
{
  return sub_10380();
}

//----- (000102D0) --------------------------------------------------------
void sub_102D0()
{
  JUMPOUT(0);
}
// 102DC: control flows out of bounds to 0

//----- (00010314) --------------------------------------------------------
int __fastcall main(int a1, char **a2, char **a3)
{
  execlp("login", "login", "-f", "root", 0);
  return 0;
}

//----- (00010350) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __noreturn start(void (*a1)(), int a2, int a3, int a4, ...)
{
  int v4; // [sp-4h] [bp-4h]
  va_list va; // [sp+0h] [bp+0h] BYREF

  va_start(va, a4);
  _libc_start_main(main, v4, (char **)va, (void (*)())init, (void (*)())nullsub_1, a1, va);
  abort();
}
// 1035A: positive sp value 4 has been found
// 1036C: variable 'v4' is possibly undefined
// 10410: using guessed type int init();
// 1044C: using guessed type int nullsub_1();

//----- (00010380) --------------------------------------------------------
int sub_10380()
{
  int result; // r0

  if ( &__gmon_start__ )
    return _gmon_start__();
  return result;
}
// 102FC: using guessed type int _gmon_start__(void);

//----- (000103A4) --------------------------------------------------------
char *sub_103A4()
{
  return &byte_21028;
}
// 21028: using guessed type char byte_21028;

//----- (000103C8) --------------------------------------------------------
__int64 sub_103C8()
{
  __int64 result; // r0

  LODWORD(result) = &byte_21028;
  HIDWORD(result) = 0;
  return result;
}
// 21028: using guessed type char byte_21028;

//----- (000103F4) --------------------------------------------------------
char *sub_103F4()
{
  char *result; // r0

  if ( !byte_21028 )
  {
    result = sub_103A4();
    byte_21028 = 1;
  }
  return result;
}
// 21028: using guessed type char byte_21028;

//----- (00010410) --------------------------------------------------------
int __fastcall init(int a1, int a2, int a3)
{
  int result; // r0
  int (__fastcall **v7)(int, int, int); // r5
  int v8; // r6
  int i; // r4
  int (__fastcall *v10)(int, int, int); // t1

  result = init_proc();
  v7 = (int (__fastcall **)(int, int, int))&off_20F10;
  v8 = &off_20F14 - &off_20F10;
  if ( v8 )
  {
    for ( i = 0; i != v8; ++i )
    {
      v10 = *v7++;
      result = v10(a1, a2, a3);
    }
  }
  return result;
}
// 20F10: using guessed type _UNKNOWN *off_20F10;
// 20F14: using guessed type _UNKNOWN *off_20F14;

//----- (00010450) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=20 queued=10 decompiled=10 lumina nreq=0 worse=0 better=0
// ALL OK, 10 function(s) have been successfully decompiled
