/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'dropbear'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct $6ECA53571B8FCC125A3088582131FB6E;
struct sockaddr;
struct $44840292B0FD4432816E14C2BB6B9957;
struct siginfo;

/* 1 */
struct Elf32_Sym
{
  unsigned __int32 st_name __offset(OFF32,0x10EA4);
  unsigned __int32 st_value __off;
  unsigned __int32 st_size;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
};

/* 2 */
struct Elf32_Rel
{
  unsigned __int32 r_offset;
  unsigned __int32 r_info;
};

/* 3 */
union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249
{
  unsigned __int32 d_val;
  unsigned __int32 d_ptr;
};

/* 4 */
struct Elf32_Dyn
{
  __int32 d_tag;
  union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249 d_un;
};

/* 5 */
struct Elf32_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file __offset(OFF32,0x10EA4);
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 6 */
struct Elf32_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name __offset(OFF32,0x10EA4);
  unsigned __int32 vna_next;
};

/* 8 */
typedef unsigned int size_t;

/* 7 */
struct iovec
{
  void *iov_base;
  size_t iov_len;
};

/* 10 */
typedef int __time_t;

/* 11 */
typedef int __suseconds_t;

/* 9 */
struct timeval
{
  __time_t tv_sec;
  __suseconds_t tv_usec;
};

/* 12 */
typedef struct $6ECA53571B8FCC125A3088582131FB6E fd_set;

/* 14 */
typedef int __fd_mask;

/* 13 */
struct $6ECA53571B8FCC125A3088582131FB6E
{
  __fd_mask __fds_bits[32];
};

/* 16 */
typedef unsigned int __socklen_t;

/* 15 */
typedef __socklen_t socklen_t;

/* 17 */
struct addrinfo
{
  int ai_flags;
  int ai_family;
  int ai_socktype;
  int ai_protocol;
  socklen_t ai_addrlen;
  struct sockaddr *ai_addr;
  char *ai_canonname;
  struct addrinfo *ai_next;
};

/* 19 */
typedef unsigned __int16 sa_family_t;

/* 18 */
struct sockaddr
{
  sa_family_t sa_family;
  char sa_data[14];
};

/* 21 */
typedef struct $44840292B0FD4432816E14C2BB6B9957 __sigset_t;

/* 20 */
typedef __sigset_t sigset_t;

/* 22 */
struct $44840292B0FD4432816E14C2BB6B9957
{
  unsigned int __val[32];
};

/* 25 */
typedef void (*__sighandler_t)(int);

/* 26 */
typedef struct siginfo siginfo_t;

/* 24 */
union sigaction::$8A6CDC2F5AA8DF854CEC54DCAF095C68
{
  __sighandler_t sa_handler;
  void (*sa_sigaction)(int, siginfo_t *, void *);
};

/* 23 */
struct sigaction
{
  union sigaction::$8A6CDC2F5AA8DF854CEC54DCAF095C68 __sigaction_handler;
  __sigset_t sa_mask;
  int sa_flags;
  void (*sa_restorer)(void);
};

/* 30 */
typedef int __pid_t;

/* 31 */
typedef unsigned int __uid_t;

/* 29 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$DDF278A5B88F81FEC3CBEE828E282CB3
{
  __pid_t si_pid;
  __uid_t si_uid;
};

/* 34 */
union sigval
{
  int sival_int;
  void *sival_ptr;
};

/* 33 */
typedef union sigval sigval_t;

/* 32 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$F43D85AC31CEBD8CC07B08111ABDF065
{
  int si_tid;
  int si_overrun;
  sigval_t si_sigval;
};

/* 35 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$002955E8B5DE3B92E30DFEF7AB65BFE2
{
  __pid_t si_pid;
  __uid_t si_uid;
  sigval_t si_sigval;
};

/* 37 */
typedef int __clock_t;

/* 36 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$353EAF26536A4016665766004ADC0BD6
{
  __pid_t si_pid;
  __uid_t si_uid;
  int si_status;
  __clock_t si_utime;
  __clock_t si_stime;
};

/* 38 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$394784BEE55B7018BCA7354475FB2ABC
{
  void *si_addr;
};

/* 39 */
struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$534EC22A0813C1325C3E7D3262B5A8D3
{
  int si_band;
  int si_fd;
};

/* 28 */
union siginfo::$0A533C95F56D7198FDCBF4ED772C5A43
{
  int _pad[29];
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$DDF278A5B88F81FEC3CBEE828E282CB3 _kill;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$F43D85AC31CEBD8CC07B08111ABDF065 _timer;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$002955E8B5DE3B92E30DFEF7AB65BFE2 _rt;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$353EAF26536A4016665766004ADC0BD6 _sigchld;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$394784BEE55B7018BCA7354475FB2ABC _sigfault;
  struct siginfo::$0A533C95F56D7198FDCBF4ED772C5A43::$534EC22A0813C1325C3E7D3262B5A8D3 _sigpoll;
};

/* 27 */
struct siginfo
{
  int si_signo;
  int si_errno;
  int si_code;
  union siginfo::$0A533C95F56D7198FDCBF4ED772C5A43 _sifields;
};

/* 40 */
typedef __time_t time_t;

/* 42 */
typedef unsigned int tcflag_t;

/* 43 */
typedef unsigned __int8 cc_t;

/* 44 */
typedef unsigned int speed_t;

/* 41 */
struct termios
{
  tcflag_t c_iflag;
  tcflag_t c_oflag;
  tcflag_t c_cflag;
  tcflag_t c_lflag;
  cc_t c_line;
  cc_t c_cc[32];
  speed_t c_ispeed;
  speed_t c_ospeed;
};

/* 45 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 46 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 47 */
typedef __n64 int8x8_t;

/* 48 */
typedef __n64 uint8x8_t;

/* 49 */
typedef __n64 int16x4_t;

/* 50 */
typedef __n64 int32x2_t;

/* 51 */
typedef __n64 uint16x4_t;

/* 52 */
typedef __n64 uint32x2_t;

/* 53 */
typedef __n128 int8x16_t;

/* 54 */
typedef __n128 int16x8_t;

/* 55 */
typedef __n128 int32x4_t;

/* 56 */
typedef __n128 int64x2_t;

/* 57 */
typedef __n128 uint8x16_t;

/* 58 */
typedef __n128 uint16x8_t;

/* 59 */
typedef __n128 uint32x4_t;

/* 60 */
typedef __n128 uint64x2_t;

/* 61 */
typedef __n64 poly8x8_t;

/* 62 */
typedef __n64 poly16x4_t;

/* 63 */
typedef __n128 poly16x8_t;

/* 64 */
typedef __n128 poly8x16_t;

/* 65 */
typedef __n64 float16x4_t;

/* 66 */
typedef __n64 float32x2_t;

/* 67 */
typedef __n128 float16x8_t;

/* 68 */
typedef __n128 float32x4_t;

/* 69 */
typedef __n128 float64x2_t;

/* 70 */
typedef __n128 poly128_t;

/* 71 */
typedef int16x4_t int16x2_t;

/* 72 */
typedef uint16x4_t uint16x2_t;

/* 73 */
typedef float16x4_t float16x2_t;

