// Data types exported from: gdb_8ec97ec8e4e68731
// Generated by Ghidra

#ifndef GDB_8EC97EC8E4E68731_TYPES_H
#define GDB_8EC97EC8E4E68731_TYPES_H

#include <stdint.h>
#include <stdbool.h>

/* ==================== Enumerations ==================== */

typedef enum {
    DT_NULL = 0,
    DT_NEEDED = 1,
    DT_PLTRELSZ = 2,
    DT_PLTGOT = 3,
    DT_HASH = 4,
    DT_STRTAB = 5,
    DT_SYMTAB = 6,
    DT_RELA = 7,
    DT_RELASZ = 8,
    DT_RELAENT = 9,
    DT_STRSZ = 10,
    DT_SYMENT = 11,
    DT_INIT = 12,
    DT_FINI = 13,
    DT_SONAME = 14,
    DT_RPATH = 15,
    DT_SYMBOLIC = 16,
    DT_REL = 17,
    DT_RELSZ = 18,
    DT_RELENT = 19,
    DT_PLTREL = 20,
    DT_DEBUG = 21,
    DT_TEXTREL = 22,
    DT_JMPREL = 23,
    DT_BIND_NOW = 24,
    DT_INIT_ARRAY = 25,
    DT_FINI_ARRAY = 26,
    DT_INIT_ARRAYSZ = 27,
    DT_FINI_ARRAYSZ = 28,
    DT_RUNPATH = 29,
    DT_FLAGS = 30,
    DT_PREINIT_ARRAY = 32,
    DT_PREINIT_ARRAYSZ = 33,
    DT_RELRSZ = 35,
    DT_RELR = 36,
    DT_RELRENT = 37,
    DT_ANDROID_REL = 1610612751,
    DT_ANDROID_RELSZ = 1610612752,
    DT_ANDROID_RELA = 1610612753,
    DT_ANDROID_RELASZ = 1610612754,
    DT_ANDROID_RELR = 1879040000,
    DT_ANDROID_RELRSZ = 1879040001,
    DT_ANDROID_RELRENT = 1879040003,
    DT_GNU_PRELINKED = 1879047669,
    DT_GNU_CONFLICTSZ = 1879047670,
    DT_GNU_LIBLISTSZ = 1879047671,
    DT_CHECKSUM = 1879047672,
    DT_PLTPADSZ = 1879047673,
    DT_MOVEENT = 1879047674,
    DT_MOVESZ = 1879047675,
    DT_FEATURE_1 = 1879047676,
    DT_POSFLAG_1 = 1879047677,
    DT_SYMINSZ = 1879047678,
    DT_SYMINENT = 1879047679,
    DT_GNU_XHASH = 1879047924,
    DT_GNU_HASH = 1879047925,
    DT_TLSDESC_PLT = 1879047926,
    DT_TLSDESC_GOT = 1879047927,
    DT_GNU_CONFLICT = 1879047928,
    DT_GNU_LIBLIST = 1879047929,
    DT_CONFIG = 1879047930,
    DT_DEPAUDIT = 1879047931,
    DT_AUDIT = 1879047932,
    DT_PLTPAD = 1879047933,
    DT_MOVETAB = 1879047934,
    DT_SYMINFO = 1879047935,
    DT_VERSYM = 1879048176,
    DT_RELACOUNT = 1879048185,
    DT_RELCOUNT = 1879048186,
    DT_FLAGS_1 = 1879048187,
    DT_VERDEF = 1879048188,
    DT_VERDEFNUM = 1879048189,
    DT_VERNEED = 1879048190,
    DT_VERNEEDNUM = 1879048191,
    DT_AUXILIARY = 2147483645,
    DT_FILTER = 2147483647,
} Elf32_DynTag_ARM;

typedef enum {
    PT_NULL = 0,
    PT_LOAD = 1,
    PT_DYNAMIC = 2,
    PT_INTERP = 3,
    PT_NOTE = 4,
    PT_SHLIB = 5,
    PT_PHDR = 6,
    PT_TLS = 7,
    PT_GNU_EH_FRAME = 1685382480,
    PT_GNU_STACK = 1685382481,
    PT_GNU_RELRO = 1685382482,
    PT_ARM_EXIDX = 1879048192,
} Elf_ProgramHeaderType_ARM;

typedef enum {
    SHT_NULL = 0,
    SHT_PROGBITS = 1,
    SHT_SYMTAB = 2,
    SHT_STRTAB = 3,
    SHT_RELA = 4,
    SHT_HASH = 5,
    SHT_DYNAMIC = 6,
    SHT_NOTE = 7,
    SHT_NOBITS = 8,
    SHT_REL = 9,
    SHT_SHLIB = 10,
    SHT_DYNSYM = 11,
    SHT_INIT_ARRAY = 14,
    SHT_FINI_ARRAY = 15,
    SHT_PREINIT_ARRAY = 16,
    SHT_GROUP = 17,
    SHT_SYMTAB_SHNDX = 18,
    SHT_ANDROID_REL = 1610612737,
    SHT_ANDROID_RELA = 1610612738,
    SHT_GNU_ATTRIBUTES = 1879048181,
    SHT_GNU_HASH = 1879048182,
    SHT_GNU_LIBLIST = 1879048183,
    SHT_CHECKSUM = 1879048184,
    SHT_SUNW_move = 1879048186,
    SHT_SUNW_COMDAT = 1879048187,
    SHT_SUNW_syminfo = 1879048188,
    SHT_GNU_verdef = 1879048189,
    SHT_GNU_verneed = 1879048190,
    SHT_GNU_versym = 1879048191,
    SHT_ARM_EXIDX = 1879048193,
    SHT_ARM_PREEMPTMAP = 1879048194,
    SHT_ARM_ATTRIBUTES = 1879048195,
    SHT_ARM_DEBUGOVERLAY = 1879048196,
    SHT_ARM_OVERLAYSECTION = 1879048197,
} Elf_SectionHeaderType_ARM;

typedef enum {
    PTRACE_TRACEME = 0,
    PTRACE_PEEKTEXT = 1,
    PTRACE_PEEKDATA = 2,
    PTRACE_PEEKUSER = 3,
    PTRACE_POKETEXT = 4,
    PTRACE_POKEDATA = 5,
    PTRACE_POKEUSER = 6,
    PTRACE_CONT = 7,
    PTRACE_KILL = 8,
    PTRACE_SINGLESTEP = 9,
    PTRACE_GETREGS = 12,
    PTRACE_SETREGS = 13,
    PTRACE_GETFPREGS = 14,
    PTRACE_SETFPREGS = 15,
    PTRACE_ATTACH = 16,
    PTRACE_DETACH = 17,
    PTRACE_GETFPXREGS = 18,
    PTRACE_SETFPXREGS = 19,
    PTRACE_SYSCALL = 24,
    PTRACE_SETOPTIONS = 16896,
    PTRACE_GETEVENTMSG = 16897,
    PTRACE_GETSIGINFO = 16898,
    PTRACE_SETSIGINFO = 16899,
} __ptrace_request;

typedef enum {
    RLIMIT_CPU = 0,
    RLIMIT_FSIZE = 1,
    RLIMIT_DATA = 2,
    RLIMIT_STACK = 3,
    RLIMIT_CORE = 4,
    __RLIMIT_RSS = 5,
    __RLIMIT_NPROC = 6,
    RLIMIT_NOFILE = 7,
    __RLIMIT_MEMLOCK = 8,
    __RLIMIT_OFILE = 8,
    RLIMIT_AS = 9,
    __RLIMIT_LOCKS = 10,
    __RLIMIT_SIGPENDING = 11,
    __RLIMIT_MSGQUEUE = 12,
    __RLIMIT_NICE = 13,
    __RLIMIT_RTPRIO = 14,
    __RLIMIT_NLIMITS = 15,
    __RLIM_NLIMITS = 16,
} __rlimit_resource;

typedef enum {
    RUSAGE_CHILDREN = -1,
    RUSAGE_SELF = 0,
    RUSAGE_THREAD = 1,
} __rusage_who;

/* ==================== Forward Declarations ==================== */

typedef struct Elf32_Dyn_ARM Elf32_Dyn_ARM;
typedef struct Elf32_Ehdr Elf32_Ehdr;
typedef struct Elf32_Phdr Elf32_Phdr;
typedef struct Elf32_Rel Elf32_Rel;
typedef struct Elf32_Shdr Elf32_Shdr;
typedef struct Elf32_Sym Elf32_Sym;
typedef struct GnuBuildId GnuBuildId;
typedef struct NoteAbiTag NoteAbiTag;
typedef struct _IO_FILE _IO_FILE;
typedef struct _IO_marker _IO_marker;
typedef struct __concurrence_lock_error __concurrence_lock_error;
typedef struct __concurrence_unlock_error __concurrence_unlock_error;
typedef struct __dirstream __dirstream;
typedef struct __fsid_t __fsid_t;
typedef struct __jmp_buf_tag __jmp_buf_tag;
typedef struct __mbstate_t __mbstate_t;
typedef struct __pthread_internal_slist __pthread_internal_slist;
typedef struct __pthread_mutex_s __pthread_mutex_s;
typedef struct __sigset_t __sigset_t;
typedef struct _struct_1032 _struct_1032;
typedef struct _struct_1033 _struct_1033;
typedef struct _struct_1034 _struct_1034;
typedef struct _struct_1035 _struct_1035;
typedef struct _struct_1036 _struct_1036;
typedef struct _struct_1037 _struct_1037;
typedef struct bad_alloc bad_alloc;
typedef struct bad_array_new_length bad_array_new_length;
typedef struct bad_cast bad_cast;
typedef struct bad_exception bad_exception;
typedef struct bad_typeid bad_typeid;
typedef struct dirent64 dirent64;
typedef struct domain_error domain_error;
typedef struct evp_pkey_ctx_st evp_pkey_ctx_st;
typedef struct fd_set fd_set;
typedef struct group group;
typedef struct hostent hostent;
typedef struct invalid_argument invalid_argument;
typedef struct iovec iovec;
typedef struct length_error length_error;
typedef struct logic_error logic_error;
typedef struct msghdr msghdr;
typedef struct out_of_range out_of_range;
typedef struct overflow_error overflow_error;
typedef struct passwd passwd;
typedef struct pollfd pollfd;
typedef struct range_error range_error;
typedef struct re_pattern_buffer re_pattern_buffer;
typedef struct re_registers re_registers;
typedef struct recursive_init_error recursive_init_error;
typedef struct regmatch_t regmatch_t;
typedef struct rlimit64 rlimit64;
typedef struct runtime_error runtime_error;
typedef struct rusage rusage;
typedef struct sigaction sigaction;
typedef struct sigaltstack sigaltstack;
typedef struct siginfo siginfo;
typedef struct sockaddr sockaddr;
typedef struct stat64 stat64;
typedef struct statfs64 statfs64;
typedef struct termios termios;
typedef struct timespec timespec;
typedef struct timeval timeval;
typedef struct timezone timezone;
typedef struct underflow_error underflow_error;

/* ==================== Structures ==================== */

struct Elf32_Dyn_ARM {
    Elf32_DynTag_ARM d_tag;  // offset: 0x0
    dword d_val;  // offset: 0x4
}; // size: 0x8

struct Elf32_Ehdr {
    byte e_ident_magic_num;  // offset: 0x0
    string e_ident_magic_str;  // offset: 0x1
    byte e_ident_class;  // offset: 0x4
    byte e_ident_data;  // offset: 0x5
    byte e_ident_version;  // offset: 0x6
    byte e_ident_osabi;  // offset: 0x7
    byte e_ident_abiversion;  // offset: 0x8
    byte e_ident_pad[7];  // offset: 0x9
    word e_type;  // offset: 0x10
    word e_machine;  // offset: 0x12
    dword e_version;  // offset: 0x14
    dword e_entry;  // offset: 0x18
    dword e_phoff;  // offset: 0x1c
    dword e_shoff;  // offset: 0x20
    dword e_flags;  // offset: 0x24
    word e_ehsize;  // offset: 0x28
    word e_phentsize;  // offset: 0x2a
    word e_phnum;  // offset: 0x2c
    word e_shentsize;  // offset: 0x2e
    word e_shnum;  // offset: 0x30
    word e_shstrndx;  // offset: 0x32
}; // size: 0x34

struct Elf32_Phdr {
    Elf_ProgramHeaderType_ARM p_type;  // offset: 0x0
    dword p_offset;  // offset: 0x4
    dword p_vaddr;  // offset: 0x8
    dword p_paddr;  // offset: 0xc
    dword p_filesz;  // offset: 0x10
    dword p_memsz;  // offset: 0x14
    dword p_flags;  // offset: 0x18
    dword p_align;  // offset: 0x1c
}; // size: 0x20

struct Elf32_Rel {
    dword r_offset;  // offset: 0x0
    dword r_info;  // offset: 0x4
}; // size: 0x8

struct Elf32_Shdr {
    dword sh_name;  // offset: 0x0
    Elf_SectionHeaderType_ARM sh_type;  // offset: 0x4
    dword sh_flags;  // offset: 0x8
    dword sh_addr;  // offset: 0xc
    dword sh_offset;  // offset: 0x10
    dword sh_size;  // offset: 0x14
    dword sh_link;  // offset: 0x18
    dword sh_info;  // offset: 0x1c
    dword sh_addralign;  // offset: 0x20
    dword sh_entsize;  // offset: 0x24
}; // size: 0x28

struct Elf32_Sym {
    dword st_name;  // offset: 0x0
    dword st_value;  // offset: 0x4
    dword st_size;  // offset: 0x8
    byte st_info;  // offset: 0xc
    byte st_other;  // offset: 0xd
    word st_shndx;  // offset: 0xe
}; // size: 0x10

struct GnuBuildId {
    dword namesz;  // offset: 0x0
    dword descsz;  // offset: 0x4
    dword type;  // offset: 0x8
    string name;  // offset: 0xc
    byte hash[20];  // offset: 0x10
}; // size: 0x24

struct NoteAbiTag {
    dword namesz;  // offset: 0x0
    dword descsz;  // offset: 0x4
    dword type;  // offset: 0x8
    string name;  // offset: 0xc
    dword abiType;  // offset: 0x10
    dword requiredKernelVersion[3];  // offset: 0x14
}; // size: 0x20

struct _IO_FILE {
    int _flags;  // offset: 0x0
    char * _IO_read_ptr;  // offset: 0x4
    char * _IO_read_end;  // offset: 0x8
    char * _IO_read_base;  // offset: 0xc
    char * _IO_write_base;  // offset: 0x10
    char * _IO_write_ptr;  // offset: 0x14
    char * _IO_write_end;  // offset: 0x18
    char * _IO_buf_base;  // offset: 0x1c
    char * _IO_buf_end;  // offset: 0x20
    char * _IO_save_base;  // offset: 0x24
    char * _IO_backup_base;  // offset: 0x28
    char * _IO_save_end;  // offset: 0x2c
    _IO_marker * _markers;  // offset: 0x30
    _IO_FILE * _chain;  // offset: 0x34
    int _fileno;  // offset: 0x38
    int _flags2;  // offset: 0x3c
    __off_t _old_offset;  // offset: 0x40
    ushort _cur_column;  // offset: 0x44
    char _vtable_offset;  // offset: 0x46
    char _shortbuf[1];  // offset: 0x47
    _IO_lock_t * _lock;  // offset: 0x48
    __off64_t _offset;  // offset: 0x50
    void * __pad1;  // offset: 0x58
    void * __pad2;  // offset: 0x5c
    void * __pad3;  // offset: 0x60
    void * __pad4;  // offset: 0x64
    size_t __pad5;  // offset: 0x68
    int _mode;  // offset: 0x6c
    char _unused2[40];  // offset: 0x70
}; // size: 0x98

struct _IO_marker {
    _IO_marker * _next;  // offset: 0x0
    _IO_FILE * _sbuf;  // offset: 0x4
    int _pos;  // offset: 0x8
}; // size: 0xc

struct __concurrence_lock_error {
    // Empty structure
}; // size: 0x1

struct __concurrence_unlock_error {
    // Empty structure
}; // size: 0x1

struct __dirstream {
    // Empty structure
}; // size: 0x1

struct __fsid_t {
    int __val[2];  // offset: 0x0
}; // size: 0x8

struct __jmp_buf_tag {
    __jmp_buf __jmpbuf;  // offset: 0x0
    int __mask_was_saved;  // offset: 0x18
    __sigset_t __saved_mask;  // offset: 0x1c
}; // size: 0x9c

struct __mbstate_t {
    int __count;  // offset: 0x0
    _union_54 __value;  // offset: 0x4
}; // size: 0x8

struct __pthread_internal_slist {
    __pthread_internal_slist * __next;  // offset: 0x0
}; // size: 0x4

struct __pthread_mutex_s {
    int __lock;  // offset: 0x0
    uint __count;  // offset: 0x4
    int __owner;  // offset: 0x8
    int __kind;  // offset: 0xc
    uint __nusers;  // offset: 0x10
    _union_13 field_20;  // offset: 0x14
}; // size: 0x18

struct __sigset_t {
    ulong __val[32];  // offset: 0x0
}; // size: 0x80

struct _struct_1032 {
    __pid_t si_pid;  // offset: 0x0
    __uid_t si_uid;  // offset: 0x4
}; // size: 0x8

struct _struct_1033 {
    int si_tid;  // offset: 0x0
    int si_overrun;  // offset: 0x4
    sigval_t si_sigval;  // offset: 0x8
}; // size: 0xc

struct _struct_1034 {
    __pid_t si_pid;  // offset: 0x0
    __uid_t si_uid;  // offset: 0x4
    sigval_t si_sigval;  // offset: 0x8
}; // size: 0xc

struct _struct_1035 {
    __pid_t si_pid;  // offset: 0x0
    __uid_t si_uid;  // offset: 0x4
    int si_status;  // offset: 0x8
    __clock_t si_utime;  // offset: 0xc
    __clock_t si_stime;  // offset: 0x10
}; // size: 0x14

struct _struct_1036 {
    void * si_addr;  // offset: 0x0
}; // size: 0x4

struct _struct_1037 {
    long si_band;  // offset: 0x0
    int si_fd;  // offset: 0x4
}; // size: 0x8

struct bad_alloc {
    // Empty structure
}; // size: 0x1

struct bad_array_new_length {
    // Empty structure
}; // size: 0x1

struct bad_cast {
    // Empty structure
}; // size: 0x1

struct bad_exception {
    // Empty structure
}; // size: 0x1

struct bad_typeid {
    // Empty structure
}; // size: 0x1

struct dirent64 {
    __ino64_t d_ino;  // offset: 0x0
    __off64_t d_off;  // offset: 0x8
    ushort d_reclen;  // offset: 0x10
    uchar d_type;  // offset: 0x12
    char d_name[256];  // offset: 0x13
}; // size: 0x118

struct domain_error {
    // Empty structure
}; // size: 0x1

struct evp_pkey_ctx_st {
    // Empty structure
}; // size: 0x1

struct fd_set {
    __fd_mask fds_bits[32];  // offset: 0x0
}; // size: 0x80

struct group {
    char * gr_name;  // offset: 0x0
    char * gr_passwd;  // offset: 0x4
    __gid_t gr_gid;  // offset: 0x8
    char * * gr_mem;  // offset: 0xc
}; // size: 0x10

struct hostent {
    char * h_name;  // offset: 0x0
    char * * h_aliases;  // offset: 0x4
    int h_addrtype;  // offset: 0x8
    int h_length;  // offset: 0xc
    char * * h_addr_list;  // offset: 0x10
}; // size: 0x14

struct invalid_argument {
    // Empty structure
}; // size: 0x1

struct iovec {
    void * iov_base;  // offset: 0x0
    size_t iov_len;  // offset: 0x4
}; // size: 0x8

struct length_error {
    // Empty structure
}; // size: 0x1

struct logic_error {
    // Empty structure
}; // size: 0x1

struct msghdr {
    void * msg_name;  // offset: 0x0
    socklen_t msg_namelen;  // offset: 0x4
    iovec * msg_iov;  // offset: 0x8
    size_t msg_iovlen;  // offset: 0xc
    void * msg_control;  // offset: 0x10
    size_t msg_controllen;  // offset: 0x14
    int msg_flags;  // offset: 0x18
}; // size: 0x1c

struct out_of_range {
    // Empty structure
}; // size: 0x1

struct overflow_error {
    // Empty structure
}; // size: 0x1

struct passwd {
    char * pw_name;  // offset: 0x0
    char * pw_passwd;  // offset: 0x4
    __uid_t pw_uid;  // offset: 0x8
    __gid_t pw_gid;  // offset: 0xc
    char * pw_gecos;  // offset: 0x10
    char * pw_dir;  // offset: 0x14
    char * pw_shell;  // offset: 0x18
}; // size: 0x1c

struct pollfd {
    int fd;  // offset: 0x0
    short events;  // offset: 0x4
    short revents;  // offset: 0x6
}; // size: 0x8

struct range_error {
    // Empty structure
}; // size: 0x1

struct re_pattern_buffer {
    uchar * buffer;  // offset: 0x0
    ulong allocated;  // offset: 0x4
    ulong used;  // offset: 0x8
    reg_syntax_t syntax;  // offset: 0xc
    char * fastmap;  // offset: 0x10
    uchar * translate;  // offset: 0x14
    size_t re_nsub;  // offset: 0x18
    uint:1 can_be_null;  // offset: 0x1c
    uint:2 regs_allocated;  // offset: 0x1c
    uint:1 fastmap_accurate;  // offset: 0x1c
    uint:1 no_sub;  // offset: 0x1c
    uint:1 not_bol;  // offset: 0x1c
    uint:1 not_eol;  // offset: 0x1c
    uint:1 newline_anchor;  // offset: 0x1c
}; // size: 0x20

struct re_registers {
    uint num_regs;  // offset: 0x0
    regoff_t * start;  // offset: 0x4
    regoff_t * end;  // offset: 0x8
}; // size: 0xc

struct recursive_init_error {
    // Empty structure
}; // size: 0x1

struct regmatch_t {
    regoff_t rm_so;  // offset: 0x0
    regoff_t rm_eo;  // offset: 0x4
}; // size: 0x8

struct rlimit64 {
    rlim64_t rlim_cur;  // offset: 0x0
    rlim64_t rlim_max;  // offset: 0x8
}; // size: 0x10

struct runtime_error {
    // Empty structure
}; // size: 0x1

struct rusage {
    timeval ru_utime;  // offset: 0x0
    timeval ru_stime;  // offset: 0x8
    long ru_maxrss;  // offset: 0x10
    long ru_ixrss;  // offset: 0x14
    long ru_idrss;  // offset: 0x18
    long ru_isrss;  // offset: 0x1c
    long ru_minflt;  // offset: 0x20
    long ru_majflt;  // offset: 0x24
    long ru_nswap;  // offset: 0x28
    long ru_inblock;  // offset: 0x2c
    long ru_oublock;  // offset: 0x30
    long ru_msgsnd;  // offset: 0x34
    long ru_msgrcv;  // offset: 0x38
    long ru_nsignals;  // offset: 0x3c
    long ru_nvcsw;  // offset: 0x40
    long ru_nivcsw;  // offset: 0x44
}; // size: 0x48

struct sigaction {
    _union_1051 __sigaction_handler;  // offset: 0x0
    __sigset_t sa_mask;  // offset: 0x4
    int sa_flags;  // offset: 0x84
    _func_4849 * sa_restorer;  // offset: 0x88
}; // size: 0x8c

struct sigaltstack {
    void * ss_sp;  // offset: 0x0
    int ss_flags;  // offset: 0x4
    size_t ss_size;  // offset: 0x8
}; // size: 0xc

struct siginfo {
    int si_signo;  // offset: 0x0
    int si_errno;  // offset: 0x4
    int si_code;  // offset: 0x8
    _union_1031 _sifields;  // offset: 0xc
}; // size: 0x80

struct sockaddr {
    sa_family_t sa_family;  // offset: 0x0
    char sa_data[14];  // offset: 0x2
}; // size: 0x10

struct stat64 {
    __dev_t st_dev;  // offset: 0x0
    uint __pad1;  // offset: 0x8
    __ino_t __st_ino;  // offset: 0xc
    __mode_t st_mode;  // offset: 0x10
    __nlink_t st_nlink;  // offset: 0x14
    __uid_t st_uid;  // offset: 0x18
    __gid_t st_gid;  // offset: 0x1c
    __dev_t st_rdev;  // offset: 0x20
    uint __pad2;  // offset: 0x28
    __off64_t st_size;  // offset: 0x30
    __blksize_t st_blksize;  // offset: 0x38
    __blkcnt64_t st_blocks;  // offset: 0x40
    timespec st_atim;  // offset: 0x48
    timespec st_mtim;  // offset: 0x50
    timespec st_ctim;  // offset: 0x58
    __ino64_t st_ino;  // offset: 0x60
}; // size: 0x68

struct statfs64 {
    int f_type;  // offset: 0x0
    int f_bsize;  // offset: 0x4
    __fsblkcnt64_t f_blocks;  // offset: 0x8
    __fsblkcnt64_t f_bfree;  // offset: 0x10
    __fsblkcnt64_t f_bavail;  // offset: 0x18
    __fsfilcnt64_t f_files;  // offset: 0x20
    __fsfilcnt64_t f_ffree;  // offset: 0x28
    __fsid_t f_fsid;  // offset: 0x30
    int f_namelen;  // offset: 0x38
    int f_frsize;  // offset: 0x3c
    int f_flags;  // offset: 0x40
    int f_spare[4];  // offset: 0x44
}; // size: 0x58

struct termios {
    tcflag_t c_iflag;  // offset: 0x0
    tcflag_t c_oflag;  // offset: 0x4
    tcflag_t c_cflag;  // offset: 0x8
    tcflag_t c_lflag;  // offset: 0xc
    cc_t c_line;  // offset: 0x10
    cc_t c_cc[32];  // offset: 0x11
    speed_t c_ispeed;  // offset: 0x34
    speed_t c_ospeed;  // offset: 0x38
}; // size: 0x3c

struct timespec {
    __time_t tv_sec;  // offset: 0x0
    long tv_nsec;  // offset: 0x4
}; // size: 0x8

struct timeval {
    __time_t tv_sec;  // offset: 0x0
    __suseconds_t tv_usec;  // offset: 0x4
}; // size: 0x8

struct timezone {
    int tz_minuteswest;  // offset: 0x0
    int tz_dsttime;  // offset: 0x4
}; // size: 0x8

struct underflow_error {
    // Empty structure
}; // size: 0x1

/* ==================== Unions ==================== */

union _union_1031 {
    int[29] _pad;
    _struct_1032 _kill;
    _struct_1033 _timer;
    _struct_1034 _rt;
    _struct_1035 _sigchld;
    _struct_1036 _sigfault;
    _struct_1037 _sigpoll;
}; // size: 0x74

union _union_1051 {
    __sighandler_t sa_handler;
    _func_4848 * sa_sigaction;
}; // size: 0x4

union _union_13 {
    int __spins;
    __pthread_slist_t __list;
}; // size: 0x4

union _union_54 {
    uint __wch;
    char[4] __wchb;
}; // size: 0x4

union pthread_mutex_t {
    __pthread_mutex_s __data;
    char[24] __size;
    long __align;
}; // size: 0x18

union sigval {
    int sival_int;
    void * sival_ptr;
}; // size: 0x4

/* ==================== Type Definitions ==================== */

typedef __dirstream DIR;
typedef evp_pkey_ctx_st EVP_PKEY_CTX;
typedef _IO_FILE FILE;
typedef void _IO_lock_t;
typedef __quad_t __blkcnt64_t;
typedef long __blksize_t;
typedef long __clock_t;
typedef int __clockid_t;
typedef __compar_fn_t * __compar_fn_t;
typedef __u_quad_t __dev_t;
typedef long __fd_mask;
typedef __u_quad_t __fsblkcnt64_t;
typedef __u_quad_t __fsfilcnt64_t;
typedef uint __gid_t;
typedef void * __gnuc_va_list;
typedef __u_quad_t __ino64_t;
typedef ulong __ino_t;
typedef int __int32_t;
typedef int[6] __jmp_buf;
typedef uint __mode_t;
typedef uint __nlink_t;
typedef __quad_t __off64_t;
typedef long __off_t;
typedef int __pid_t;
typedef __pthread_internal_slist __pthread_slist_t;
typedef longlong __quad_t;
typedef __u_quad_t __rlim64_t;
typedef __rlimit_resource __rlimit_resource_t;
typedef __rusage_who __rusage_who_t;
typedef __sighandler_t * __sighandler_t;
typedef uint __socklen_t;
typedef int __ssize_t;
typedef long __suseconds_t;
typedef long __time_t;
typedef timezone * __timezone_ptr_t;
typedef ulong __u_long;
typedef ulonglong __u_quad_t;
typedef uint __uid_t;
typedef uint __useconds_t;
typedef uchar cc_t;
typedef __clockid_t clockid_t;
typedef void * iconv_t;
typedef int intptr_t;
typedef __mbstate_t mbstate_t;
typedef ulong nfds_t;
typedef int nl_item;
typedef ulong reg_syntax_t;
typedef re_pattern_buffer regex_t;
typedef int regoff_t;
typedef __rlim64_t rlim64_t;
typedef ushort sa_family_t;
typedef siginfo siginfo_t;
typedef __sigset_t sigset_t;
typedef sigval sigval_t;
typedef ulong size_t;
typedef __socklen_t socklen_t;
typedef uint speed_t;
typedef __ssize_t ssize_t;
typedef uint tcflag_t;
typedef __time_t time_t;
typedef __u_long u_long;
typedef ulong wctype_t;
typedef uint wint_t;

/* ==================== Function Prototypes ==================== */

int __compar_fn_t(void * param0, void * param1);
void __sighandler_t(int param0);
void _func_4848(int param0, siginfo_t * param1, void * param2);
void _func_4849(void);

#endif // GDB_8EC97EC8E4E68731_TYPES_H
