//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <arpa/inet.h>
#include <assert.h>
#include <ctype.h>
#include <pthread.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_1079c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
char *function_107bc(char *haystack, char *needle);
int32_t function_107c8(char *format, ...);
int32_t function_107d4(int32_t fd, int32_t *buf, int32_t nbytes);
void function_107e0(char *s);
int32_t function_107ec(int32_t fd, struct sockaddr *addr, int32_t *addr_len);
int32_t function_107f8(int32_t *ptr, int32_t size, int32_t n,
                       struct _IO_FILE *s);
char *function_10804(char *dest, char *src);
int32_t function_10810(int32_t *newthread, int32_t *attr,
                       int32_t *(*start_routine)(int32_t *), int32_t *arg);
int32_t function_1081c(char *s);
int32_t function_10828(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_10834(char *command);
void function_10840(void);
int16_t **function_1084c(void);
void function_10858(int32_t status);
int32_t function_10864(char *s);
int32_t function_10870(int32_t fd, struct sockaddr *addr, int32_t len);
int32_t *function_1087c(int32_t *s, int32_t c, int32_t n);
int32_t function_10888(int32_t fd, int32_t *buf, int32_t n);
int32_t function_10894(char *name, int32_t type);
void function_108a0(int32_t *retval);
int32_t function_108ac(int32_t fd, int32_t how);
int32_t function_108b8(int32_t fd, int32_t n);
int32_t function_108c4(char *s, char *format, ...);
int32_t function_108d0(int32_t domain, int32_t type, int32_t protocol);
int32_t function_108dc(char *cp);
void function_108e8(void);
int32_t function_108f4(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_10900(int32_t fd);
int32_t function_1090c(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_10918(int32_t fd, struct sockaddr *addr, int32_t len);
void function_10924(char *assertion, char *file, int32_t line, char *function);
int32_t function_10930(int32_t i_a1, int32_t i_a2);
int32_t function_10ba4(int32_t i_a1, int32_t i_a2);
int32_t function_10bb0(void);
int32_t function_10bd4(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_10c28(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_10c3c(void);
int32_t function_10c40(char *p_a1);
int32_t function_10c8c(int32_t i_a1);
int32_t function_10eb8(int32_t i_a1);
int32_t function_10fd0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_1100c(void);
int32_t function_11010(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = -0x1cae0000;   // 0x10bc0
int32_t i_g2 = 0x10c3d;       // 0x21f08
struct _IO_FILE *p_g3 = NULL; // 0x22098
int32_t i_g4;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t i_a1, int32_t i_a2, char **p_a3,
                          void (*p_a4)(), void (*p_a5)(), void (*p_a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1079c - 0x107a8
int32_t function_1079c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x1079c
    return function_10bb0();
}

// Address range: 0x107bc - 0x107c8
char *function_107bc(char *haystack, char *needle) {
    // 0x107bc
    return strstr(haystack, needle);
}

// Address range: 0x107c8 - 0x107d4
int32_t function_107c8(char *format, ...) {
    // 0x107c8
    return printf(format);
}

// Address range: 0x107d4 - 0x107e0
int32_t function_107d4(int32_t fd, int32_t *buf, int32_t nbytes) {
    // 0x107d4
    return read(fd, buf, nbytes);
}

// Address range: 0x107e0 - 0x107ec
void function_107e0(char *s) {
    // 0x107e0
    perror(s);
}

// Address range: 0x107ec - 0x107f8
int32_t function_107ec(int32_t fd, struct sockaddr *addr, int32_t *addr_len) {
    // 0x107ec
    return accept(fd, addr, addr_len);
}

// Address range: 0x107f8 - 0x10804
int32_t function_107f8(int32_t *ptr, int32_t size, int32_t n,
                       struct _IO_FILE *s) {
    // 0x107f8
    return fwrite(ptr, size, n, s);
}

// Address range: 0x10804 - 0x10810
char *function_10804(char *dest, char *src) {
    // 0x10804
    return strcpy(dest, src);
}

// Address range: 0x10810 - 0x1081c
int32_t function_10810(int32_t *newthread, int32_t *attr,
                       int32_t *(*start_routine)(int32_t *), int32_t *arg) {
    // 0x10810
    return pthread_create(newthread, attr, start_routine, arg);
}

// Address range: 0x1081c - 0x10828
int32_t function_1081c(char *s) {
    // 0x1081c
    return puts(s);
}

// Address range: 0x10828 - 0x10834
int32_t function_10828(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x10828
    return __libc_start_main(main, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x10834 - 0x10840
int32_t function_10834(char *command) {
    // 0x10834
    return system(command);
}

// Address range: 0x10840 - 0x1084c
void function_10840(void) {
    // 0x10840
    __gmon_start__();
}

// Address range: 0x1084c - 0x10858
int16_t **function_1084c(void) {
    // 0x1084c
    return __ctype_b_loc();
}

// Address range: 0x10858 - 0x10864
void function_10858(int32_t status) {
    // 0x10858
    exit(status);
}

// Address range: 0x10864 - 0x10870
int32_t function_10864(char *s) {
    // 0x10864
    return strlen(s);
}

// Address range: 0x10870 - 0x1087c
int32_t function_10870(int32_t fd, struct sockaddr *addr, int32_t len) {
    // 0x10870
    return bind(fd, addr, len);
}

// Address range: 0x1087c - 0x10888
int32_t *function_1087c(int32_t *s, int32_t c, int32_t n) {
    // 0x1087c
    return memset(s, c, n);
}

// Address range: 0x10888 - 0x10894
int32_t function_10888(int32_t fd, int32_t *buf, int32_t n) {
    // 0x10888
    return write(fd, buf, n);
}

// Address range: 0x10894 - 0x108a0
int32_t function_10894(char *name, int32_t type) {
    // 0x10894
    return access(name, type);
}

// Address range: 0x108a0 - 0x108ac
void function_108a0(int32_t *retval) {
    // 0x108a0
    pthread_exit(retval);
}

// Address range: 0x108ac - 0x108b8
int32_t function_108ac(int32_t fd, int32_t how) {
    // 0x108ac
    return shutdown(fd, how);
}

// Address range: 0x108b8 - 0x108c4
int32_t function_108b8(int32_t fd, int32_t n) {
    // 0x108b8
    return listen(fd, n);
}

// Address range: 0x108c4 - 0x108d0
int32_t function_108c4(char *s, char *format, ...) {
    // 0x108c4
    return sprintf(s, format);
}

// Address range: 0x108d0 - 0x108dc
int32_t function_108d0(int32_t domain, int32_t type, int32_t protocol) {
    // 0x108d0
    return socket(domain, type, protocol);
}

// Address range: 0x108dc - 0x108e8
int32_t function_108dc(char *cp) {
    // 0x108dc
    return inet_addr(cp);
}

// Address range: 0x108e8 - 0x108f4
void function_108e8(void) {
    // 0x108e8
    abort();
}

// Address range: 0x108f4 - 0x10900
int32_t function_108f4(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x108f4
    return recv(fd, buf, n, flags);
}

// Address range: 0x10900 - 0x1090c
int32_t function_10900(int32_t fd) {
    // 0x10900
    return close(fd);
}

// Address range: 0x1090c - 0x10918
int32_t function_1090c(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x1090c
    return send(fd, buf, n, flags);
}

// Address range: 0x10918 - 0x10924
int32_t function_10918(int32_t fd, struct sockaddr *addr, int32_t len) {
    // 0x10918
    return connect(fd, addr, len);
}

// Address range: 0x10924 - 0x10930
void function_10924(char *assertion, char *file, int32_t line, char *function) {
    // 0x10924
    __assert_fail(assertion, file, line, function);
}

// Address range: 0x10930 - 0x10b7c
int32_t function_10930(int32_t i_a1, int32_t i_a2) {
    char *p_v1 = (char *)i_a2;            // 0x1094c
    char *p_v2 = strstr(p_v1, "daemonc"); // 0x1094c
    if (p_v2 != NULL) {
        // 0x10ab0
        return function_10eb8(*(int32_t *)(i_a2 + 4));
    }
    // 0x10958
    if (strstr(p_v1, "daemons") == NULL) {
        // 0x10ae0
        puts("Cannot Find Command!\r");
        // 0x10ab0
        return -1;
    }
    int32_t i_v3 = socket(AF_INET, SOCK_STREAM, (int32_t)p_v2); // 0x1097c
    if (i_v3 == -1) {
        // 0x10b10
        __assert_fail("sockfd_server != -1", "update-daemon.c", 164,
                      "ProcessServer");
        // 0x10b2c
        fwrite((int32_t *)"listen error!\n", 1, 14, p_g3);
        exit(1);
        // UNREACHABLE
    }
    int16_t i_v4 = 2; // bp-56, 0x10998
    inet_addr("127.0.0.1");
    printf("Will Listening To Port[%d]\r\n", function_10c40("22322"));
    if (bind(i_v3, (struct sockaddr *)&i_v4, 16) == -1) {
        // 0x10b54
        fwrite((int32_t *)"bind error!\n", 1, 12, p_g3);
        exit(1);
        return &i_g4;
    }
    // 0x109f0
    if (listen(i_v3, 512) == -1) {
        // 0x10b2c
        fwrite((int32_t *)"listen error!\n", 1, 14, p_g3);
        exit(1);
        // UNREACHABLE
    }
    while (true) {
        // 0x10a24
        puts("waiting for new connection...");
        int32_t i_v5 = 16; // bp-64, 0x10a3c
        int32_t i_v6;      // bp-40, 0x10930
        int32_t i_v7 = accept(i_v3, (struct sockaddr *)&i_v6, &i_v5); // 0x10a40
        int32_t i_v8 = i_v7; // bp-68, 0x10a48
        if (i_v7 == -1) {
            // 0x10ac4
            fwrite((int32_t *)"Accept error!\n", 1, 14, p_g3);
        } else {
            // 0x10a50
            puts("A new connection occurs!");
            int32_t i_v9; // bp-60, 0x10930
            if (pthread_create(&i_v9, NULL, (int32_t * (*)(int32_t *))0x10c8c,
                               &i_v8) == -1) {
                // break -> 0x10a74
                break;
            }
        }
    }
    // 0x10a74
    fwrite((int32_t *)"pthread_create error!\n", 1, 22, p_g3);
    if (shutdown(i_v3, SHUT_WR) != -1) {
        // 0x10aa0
        puts("Server shuts down");
        // 0x10ab0
        return 0;
    }
    // 0x10af4
    __assert_fail("ret != -1", "update-daemon.c", 206, "ProcessServer");
    // 0x10b10
    __assert_fail("sockfd_server != -1", "update-daemon.c", 164,
                  "ProcessServer");
    // 0x10b2c
    fwrite((int32_t *)"listen error!\n", 1, 14, p_g3);
    exit(1);
    // UNREACHABLE
}

// Address range: 0x10b80 - 0x10ba4
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10b80
    int32_t i_v1; // 0x10b80
    __libc_start_main(0x10930, i_a2, (char **)&i_v1, (void (*)())0x10fd1,
                      (void (*)())0x10930, (void (*)())i_a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x10ba4 - 0x10ba8
int32_t function_10ba4(int32_t i_a1, int32_t i_a2) {
    // 0x10ba4
    return i_a1;
}

// Address range: 0x10bb0 - 0x10bcc
int32_t function_10bb0(void) {
    int32_t i_v1 =
        *(int32_t *)((int32_t)&i_g1 + (int32_t) ":'%s'\r\n" + 136); // 0x10bbc
    if (i_v1 == 0) {
        int32_t i_v2; // 0x10bb0
        return i_v2;
    }
    // 0x10bc8
    __gmon_start__();
    return &i_g4;
}

// Address range: 0x10bd4 - 0x10c28
int32_t function_10bd4(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x10bd4
    int32_t i_v1; // 0x10bd4
    int32_t i_v2 = i_v1;
    bool i_v3; // 0x10bd4
    if (i_v3) {
        return i_a1;
    }
    bool i_v4; // 0x10bd4
    if (!i_v3) {
        int32_t i_v5 = 0x100001 * i_v2 & -1 - 0x400000 * i_v2; // 0x10c0c
        i_v4 = i_v5 < 0;
        if (i_v5 == 0) {
            return unknown_240();
        }
    }
    // 0x10c1c
    if (i_v4 != i_v3) {
        __asm_svclt(0x4770);
    }
    float64_t f_v6; // 0x10bd4
    __asm_vqrshl_s8(f_v6, f_v6);
    return i_a1;
}

// Address range: 0x10c28 - 0x10c3c
int32_t function_10c28(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    char *p_v1 = (char *)(0x40000 * i_a4 | 0x20000); // 0x10c2e
    int32_t i_v2 = i_a1;                             // 0x10c30
    if (*p_v1 == 0) {
        // 0x10c32
        i_v2 = function_10bd4(i_a1, i_a2, i_a3, 0);
        *p_v1 = 1;
    }
    // 0x10c3a
    return i_v2;
}

// Address range: 0x10c3c - 0x10c3e
int32_t function_10c3c(void) {
    // 0x10c3c
    int32_t i_v1; // 0x10c3c
    return i_v1;
}

// Address range: 0x10c40 - 0x10c8c
int32_t function_10c40(char *p_a1) {
    int32_t i_v1 = (int32_t)p_a1;
    int32_t i_v2 = strlen(p_a1);    // 0x10c48
    int32_t i_v3 = i_v1 - 2 + i_v2; // 0x10c54
    int32_t i_v4 = i_v1 - 1;
    int32_t i_v5 = -48; // 0x10c7c
    if (i_v4 == i_v3) {
        // 0x10c80
        return (int32_t) * (char *)(i_v2 + i_v4) - 48;
    }
    int32_t i_v6 = i_v4; // 0x10c7c
    i_v6++;
    i_v5 = 10 * (i_v5 + (int32_t) * (char *)i_v6) - 48;
    while (i_v6 != i_v3) {
        // 0x10c64
        i_v6++;
        i_v5 = 10 * (i_v5 + (int32_t) * (char *)i_v6) - 48;
    }
    // 0x10c80
    return i_v5 + (int32_t) * (char *)(i_v2 + i_v4);
}

// Address range: 0x10c8c - 0x10eb8
int32_t function_10c8c(int32_t i_a1) {
    // 0x10c8c
    puts("New Thread!\r");
    int32_t i_v1 = 0;                               // bp-2064, 0x10cb4
    int32_t i_v2;                                   // bp-2060, 0x10c8c
    int32_t i_v3 = (int32_t)memset(&i_v2, 0, 1020); // 0x10cb8
    read(i_v3, &i_v1, 1024);
    printf("Recv:'%s'\r\n", &i_v1);
    int32_t i_v4 = access((char *)&i_v1, F_OK); // 0x10ce8
    int32_t i_v5 = 0;                           // 0x10cf0
    int32_t i_v6 = i_a1;                        // 0x10cf0
    int32_t i_v7;                               // 0x10c8c
    int32_t i_v8;                               // 0x10c8c
    int32_t i_v9;                               // bp-2080, 0x10c8c
    if (i_v4 == 0) {
        int32_t i_v10 = i_v1 % 256; // 0x10cf4
        int32_t i_v11 = i_a1;       // 0x10cfc
        if (i_v10 != 0) {
            int32_t i_v12 = (int32_t)*__ctype_b_loc(); // 0x10d04
            int32_t i_v13 = &i_v1;                     // 0x10d08
            uint16_t i_v14 = *(int16_t *)(2 * i_v10 + i_v12) & 8;
            int32_t i_v15 = i_v14; // 0x10d14
            uint32_t i_v16;        // 0x10d24
            if (i_v10 != 95 && i_v14 == 0) {
                // 0x10d24
                i_v16 = i_v10 - 45;
                if (i_v16 != 2 && i_v16 >= 2) {
                    // 0x10d30
                    puts("Invalid client content.");
                    close(i_v3);
                    pthread_exit((int32_t *)i_v15);
                }
            }
            // 0x10d4c
            i_v13++;
            unsigned char i_v17 = *(char *)i_v13; // 0x10d4c
            i_v11 = i_v15;
            while (i_v17 != 0) {
                int32_t i_v18 = i_v17;
                i_v14 = *(int16_t *)(2 * i_v18 + i_v12) & 8;
                i_v15 = i_v14;
                if (i_v18 != 95 && i_v14 == 0) {
                    // 0x10d24
                    i_v16 = i_v18 - 45;
                    if (i_v16 != 2 && i_v16 >= 2) {
                        // 0x10d30
                        puts("Invalid client content.");
                        close(i_v3);
                        pthread_exit((int32_t *)i_v15);
                    }
                }
                // 0x10d4c
                i_v13++;
                i_v17 = *(char *)i_v13;
                i_v11 = i_v15;
            }
        }
        char *p_v19 = (char *)0x7273752f; // bp-1040, 0x10d68
        char i_v20 = 0;                   // bp-1016, 0x10d78
        int32_t i_v21;                    // bp-1015, 0x10c8c
        memset(&i_v21, 0, 999);
        strcpy(&i_v20, (char *)&i_v1);
        i_v9 = 0x656d6f43;
        int32_t i_v22 = system((char *)&p_v19); // 0x10db8
        if (i_v22 == -1) {
            // 0x10e74
            puts("system err!\r");
            i_v9 = 0x303035;
            i_v5 = -1;
            i_v6 = i_v11;
            goto lab_0x10e04;
        } else {
            int32_t i_v23 = __asm_ubfx(i_v22, 8, 8); // 0x10dd4
            printf("system status:[%d]\r\n");
            i_v7 = i_v22;
            i_v8 = i_v23;
            if (i_v22 % 128 == 0) {
                if (i_v23 == 0) {
                    // 0x10dec
                    puts("Shell Exec Successfully!\r");
                    i_v9 = 0x303032;
                    i_v5 = i_v22;
                    i_v6 = 0;
                } else {
                    // 0x10e90
                    printf("Shell Execute Failed, Ret[%d]\r\n", i_v23);
                    sprintf((char *)&i_v9, "%d", i_v23);
                    i_v5 = i_v22;
                    i_v6 = i_v23;
                }
                goto lab_0x10e04;
            } else {
                goto lab_0x10e4c;
            }
        }
    } else {
        goto lab_0x10e2c;
    }
lab_0x10e2c:
    // 0x10e2c
    printf("File does not exist: %s\n", &i_v1);
    close(i_v3);
    pthread_exit((int32_t *)i_v5);
    i_v7 = i_v5;
    i_v8 = i_v6;
    goto lab_0x10e4c;
lab_0x10e4c:
    // 0x10e4c
    printf("Other Exit Ret[%d]\r\n", i_v8);
    sprintf((char *)&i_v9, "6%d", i_v8);
    i_v5 = i_v7;
    i_v6 = i_v8;
    goto lab_0x10e04;
lab_0x10e04:
    // 0x10e04
    write(i_v3, &i_v9, strlen((char *)&i_v9) + 1);
    close(i_v3);
    pthread_exit(NULL);
    goto lab_0x10e2c;
}

// Address range: 0x10eb8 - 0x10fd0
int32_t function_10eb8(int32_t i_a1) {
    // 0x10eb8
    if (i_a1 == 0) {
        // 0x10f98
        return -3;
    }
    int32_t i_v1 = 2; // bp-1056, 0x10ed8
    inet_addr("127.0.0.1");
    function_10c40("22322");
    int32_t i_v2 = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x10f10
    if (i_v2 < 0) {
        // 0x10fa8
        perror("socket err:");
        // 0x10f98
        return -1;
    }
    // 0x10f1c
    if (connect(i_v2, (struct sockaddr *)&i_v1, 16) < 0) {
        // 0x10fbc
        perror("connect err:");
        // 0x10f98
        return -2;
    }
    // 0x10f30
    send(i_v2, (int32_t *)i_a1, strlen((char *)i_a1) + 1, 0);
    int32_t i_v3 = 0; // bp-1040, 0x10f58
    int32_t i_v4;     // bp-1036, 0x10eb8
    memset(&i_v4, 0, 1020);
    uint32_t i_v5 = recv(i_v2, &i_v3, 1024, 0); // 0x10f70
    int32_t i_v6 = -3;                          // 0x10f78
    if (i_v5 >= 1) {
        // 0x10f7c
        int32_t i_v7; // bp-16, 0x10eb8
        *(char *)((int32_t)&i_v7 - 1024 + i_v5) = 0;
        int32_t i_v8 = function_10c40((char *)&i_v3); // 0x10f8c
        i_v6 = i_v8 == 200 ? 0 : i_v8;
    }
    // 0x10f98
    return i_v6;
}

// Address range: 0x10fd0 - 0x11004
int32_t function_10fd0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_1079c(i_a1, i_a2, i_a3, i_a4); // 0x10fe0
    return 0x21f0a - (int32_t)&i_g2 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x1100c - 0x1100e
int32_t function_1100c(void) {
    // 0x1100c
    int32_t i_v1; // 0x1100c
    return i_v1;
}

// Address range: 0x11010 - 0x11018
int32_t function_11010(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x11010
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 45
