//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_105f4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10614(void);
int32_t function_10620(void);
int32_t function_1062c(void);
int32_t function_10638(void);
int32_t function_10644(void);
int32_t function_10650(void);
int32_t function_1065c(void);
int32_t function_10668(void);
int32_t function_10674(void);
int32_t function_10680(void);
int32_t function_1068c(void);
int32_t function_10698(void);
int32_t function_106a4(void);
int32_t function_106b0(void);
int32_t function_106bc(void);
int32_t function_106c8(void);
int32_t function_106d4(void);
int32_t function_106e0(void);
int32_t function_106ec(void);
int32_t function_106f8(void);
int32_t function_10704(void);
int32_t function_10710(void);
int32_t function_1071c(void);
int32_t function_10728(void);
int32_t function_10764(void);
int32_t function_10788(void);
int32_t function_107ac(void);
int32_t function_107d6(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_107e6(int32_t i_a1);
int32_t function_107f0(int32_t i_a1, int32_t i_a2);
int32_t function_107f6(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10802(void);
int32_t function_10804(int32_t i_a1);
int32_t function_10810(void);
int32_t function_10814(int32_t i_a1);
int32_t function_109ec(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_10dec(int32_t i_a1);
int32_t function_10eac(int32_t i_a1, int32_t i_a2);
int32_t function_110f8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_1113c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t unknown_240(int32_t i_a1);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x107d9; // 0x2128c
int32_t i_g2 = 0;       // 0x213e8
int32_t i_g3 = 0;       // 0x21400

// ------------------------ Functions -------------------------

// Address range: 0x105f4 - 0x10600
int32_t function_105f4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x105f4
    return function_10764();
}

// Address range: 0x10614 - 0x10620
int32_t function_10614(void) {
    // 0x10614
    int32_t i_v1; // 0x10614
    return i_v1;
}

// Address range: 0x10620 - 0x1062c
int32_t function_10620(void) {
    // 0x10620
    int32_t i_v1; // 0x10620
    return i_v1;
}

// Address range: 0x1062c - 0x10638
int32_t function_1062c(void) {
    // 0x1062c
    int32_t i_v1; // 0x1062c
    return i_v1;
}

// Address range: 0x10638 - 0x10644
int32_t function_10638(void) {
    // 0x10638
    int32_t i_v1; // 0x10638
    return i_v1;
}

// Address range: 0x10644 - 0x10650
int32_t function_10644(void) {
    // 0x10644
    int32_t i_v1; // 0x10644
    return i_v1;
}

// Address range: 0x10650 - 0x1065c
int32_t function_10650(void) {
    // 0x10650
    int32_t i_v1; // 0x10650
    return i_v1;
}

// Address range: 0x1065c - 0x10668
int32_t function_1065c(void) {
    // 0x1065c
    int32_t i_v1; // 0x1065c
    return i_v1;
}

// Address range: 0x10668 - 0x10674
int32_t function_10668(void) {
    // 0x10668
    int32_t i_v1; // 0x10668
    return i_v1;
}

// Address range: 0x10674 - 0x10680
int32_t function_10674(void) {
    // 0x10674
    int32_t i_v1; // 0x10674
    return i_v1;
}

// Address range: 0x10680 - 0x1068c
int32_t function_10680(void) {
    // 0x10680
    int32_t i_v1; // 0x10680
    return i_v1;
}

// Address range: 0x1068c - 0x10698
int32_t function_1068c(void) {
    // 0x1068c
    int32_t i_v1; // 0x1068c
    return i_v1;
}

// Address range: 0x10698 - 0x106a4
int32_t function_10698(void) {
    // 0x10698
    int32_t i_v1; // 0x10698
    return i_v1;
}

// Address range: 0x106a4 - 0x106b0
int32_t function_106a4(void) {
    // 0x106a4
    int32_t i_v1; // 0x106a4
    return i_v1;
}

// Address range: 0x106b0 - 0x106bc
int32_t function_106b0(void) {
    // 0x106b0
    int32_t i_v1; // 0x106b0
    return i_v1;
}

// Address range: 0x106bc - 0x106c8
int32_t function_106bc(void) {
    // 0x106bc
    int32_t i_v1; // 0x106bc
    return i_v1;
}

// Address range: 0x106c8 - 0x106d4
int32_t function_106c8(void) {
    // 0x106c8
    int32_t i_v1; // 0x106c8
    return i_v1;
}

// Address range: 0x106d4 - 0x106e0
int32_t function_106d4(void) {
    // 0x106d4
    int32_t i_v1; // 0x106d4
    return i_v1;
}

// Address range: 0x106e0 - 0x106ec
int32_t function_106e0(void) {
    // 0x106e0
    int32_t i_v1; // 0x106e0
    return i_v1;
}

// Address range: 0x106ec - 0x106f8
int32_t function_106ec(void) {
    // 0x106ec
    int32_t i_v1; // 0x106ec
    return i_v1;
}

// Address range: 0x106f8 - 0x10704
int32_t function_106f8(void) {
    // 0x106f8
    int32_t i_v1; // 0x106f8
    return i_v1;
}

// Address range: 0x10704 - 0x10710
int32_t function_10704(void) {
    // 0x10704
    int32_t i_v1; // 0x10704
    return i_v1;
}

// Address range: 0x10710 - 0x1071c
int32_t function_10710(void) {
    // 0x10710
    int32_t i_v1; // 0x10710
    return i_v1;
}

// Address range: 0x1071c - 0x10728
int32_t function_1071c(void) {
    // 0x1071c
    int32_t i_v1; // 0x1071c
    return i_v1;
}

// Address range: 0x10728 - 0x10734
int32_t function_10728(void) {
    // 0x10728
    int32_t i_v1; // 0x10728
    return i_v1;
}

// Address range: 0x10734 - 0x1075c
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10734
    function_10668();
    return function_106f8();
}

// Address range: 0x10764 - 0x10780
int32_t function_10764(void) {
    // 0x10764
    if (i_g2 == 0) {
        int32_t i_v1; // 0x10764
        return i_v1;
    }
    // 0x1077c
    return function_10680();
}

// Address range: 0x10788 - 0x107a6
int32_t function_10788(void) {
    // 0x10788
    return 0x213f4;
}

// Address range: 0x107ac - 0x107d6
int32_t function_107ac(void) {
    // 0x107ac
    return 0x213f4;
}

// Address range: 0x107d6 - 0x107e6
int32_t function_107d6(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x107d6
    int32_t i_v1; // 0x107d6
    bool i_v2;    // 0x107d6
    if (!i_v2) {
        return i_a1;
    }
    // 0x107de
    if (i_v2) {
        *(int32_t *)i_a3 = 0x107e4;
    }
    int32_t i_v3 = i_a1; // 0x107e2
    return i_v3;
}

// Address range: 0x107e6 - 0x107f0
int32_t function_107e6(int32_t i_a1) {
    int32_t i_v1 = function_10788(); // 0x107e6
    int32_t i_v2;                    // 0x107e6
    *(char *)i_v2 = 1;
    return i_v1;
}

// Address range: 0x107f0 - 0x107f4
int32_t function_107f0(int32_t i_a1, int32_t i_a2) {
    // 0x107f0
    return i_a1;
}

// Address range: 0x107f6 - 0x10802
int32_t function_107f6(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x107f6
    bool i_v1; // 0x107f6
    if (i_v1) {
        return i_a1;
    }
    int32_t i_v2 = i_a1; // 0x107fa
    int32_t i_v3;        // 0x107f6
    int16_t i_v4 = i_v3; // 0x107fa
    if (i_v1) {
        *(int16_t *)i_v3 = i_v4;
    }
    return i_v2;
}

// Address range: 0x10802 - 0x10804
int32_t function_10802(void) {
    // 0x10802
    return function_107ac();
}

// Address range: 0x10804 - 0x10810
int32_t function_10804(int32_t i_a1) {
    // 0x10804
    bool i_v1; // 0x10804
    if (i_v1) {
        return unknown_240(i_a1);
    }
    // 0x1080c
    return i_a1;
}

// Address range: 0x10810 - 0x10814
int32_t function_10810(void) {
    // 0x10810
    int32_t i_v1; // 0x10810
    return i_v1;
}

// Address range: 0x10814 - 0x109ec
int32_t function_10814(int32_t i_a1) {
    // 0x10814
    if (i_a1 == 0) {
        // 0x109e4
        return 0;
    }
    int32_t i_v1 = function_106a4(); // 0x10834
    char *p_v2 = (char *)i_v1;       // 0x10838
    char *p_v3 = p_v2;               // 0x10844
    if (i_v1 != 0) {
        // 0x10848
        *p_v2 = 0;
        p_v3 = (char *)(i_v1 + 1);
    }
    char *p_v4 = (char *)i_a1; // 0x10860
    char *p_v5 = p_v4;         // 0x10868
    int32_t i_v6 = i_v1;       // 0x10868
    int32_t i_v7;              // 0x10814
    char *p_v8;                // 0x10814
    char *p_v9;                // 0x10814
    int32_t i_v10;             // 0x10814
    char *p_v11;               // 0x108d4
    int32_t i_v12;             // 0x1088c
    char *p_v13;               // 0x10890
    int32_t i_v14;             // 0x109a4
    int32_t i_v15;             // 0x108d0
    if (!((i_a1 == 0 | *p_v4 == 0))) {
        i_v10 = 0;
        i_v12 = function_106a4();
        p_v13 = (char *)i_v12;
        p_v8 = p_v13;
        if (i_v12 != 0) {
            // 0x108a0
            *p_v13 = 0;
            p_v8 = (char *)(i_v12 + 1);
        }
        // 0x108b4
        i_v7 = i_v12;
        if (*p_v5 != 0) {
            // 0x108c4
            i_v15 = function_106a4();
            p_v11 = (char *)i_v15;
            p_v9 = p_v11;
            if (i_v15 != 0) {
                // 0x108e4
                *p_v11 = 0;
                p_v9 = (char *)(i_v15 + 1);
            }
            if (i_v10 == 0) {
                // 0x10904
                if (p_v9 != NULL) {
                    // 0x10910
                    function_1068c();
                }
                // 0x1094c
                function_1062c();
            }
            // 0x10960
            i_v7 = function_1062c();
        }
        // 0x10998
        i_v14 = i_v10 + 1;
        p_v5 = p_v8;
        while (p_v8 != NULL) {
            // 0x10880
            i_v10 = i_v14;
            i_v12 = function_106a4();
            p_v13 = (char *)i_v12;
            p_v8 = p_v13;
            if (i_v12 != 0) {
                // 0x108a0
                *p_v13 = 0;
                p_v8 = (char *)(i_v12 + 1);
            }
            // 0x108b4
            i_v7 = i_v12;
            if (*p_v5 != 0) {
                // 0x108c4
                i_v15 = function_106a4();
                p_v11 = (char *)i_v15;
                p_v9 = p_v11;
                if (i_v15 != 0) {
                    // 0x108e4
                    *p_v11 = 0;
                    p_v9 = (char *)(i_v15 + 1);
                }
                if (i_v10 == 0) {
                    // 0x10904
                    if (p_v9 != NULL) {
                        // 0x10910
                        function_1068c();
                    }
                    // 0x1094c
                    function_1062c();
                }
                // 0x10960
                i_v7 = function_1062c();
            }
            // 0x10998
            i_v14 = i_v10 + 1;
            p_v5 = p_v8;
        }
        // 0x109b8
        i_v6 = i_v7;
        if (i_v14 >= 1) {
            // 0x109c4
            i_v6 = function_10650();
        }
    }
    int32_t i_v16 = (int32_t)p_v3; // 0x109e0
    while (p_v3 != NULL) {
        // 0x10828
        i_v1 = function_106a4();
        p_v2 = (char *)i_v1;
        p_v3 = p_v2;
        if (i_v1 != 0) {
            // 0x10848
            *p_v2 = 0;
            p_v3 = (char *)(i_v1 + 1);
        }
        // 0x1085c
        p_v4 = (char *)i_v16;
        p_v5 = p_v4;
        i_v6 = i_v1;
        if (!((i_v16 == 0 | *p_v4 == 0))) {
            i_v10 = 0;
            i_v12 = function_106a4();
            p_v13 = (char *)i_v12;
            p_v8 = p_v13;
            if (i_v12 != 0) {
                // 0x108a0
                *p_v13 = 0;
                p_v8 = (char *)(i_v12 + 1);
            }
            // 0x108b4
            i_v7 = i_v12;
            if (*p_v5 != 0) {
                // 0x108c4
                i_v15 = function_106a4();
                p_v11 = (char *)i_v15;
                p_v9 = p_v11;
                if (i_v15 != 0) {
                    // 0x108e4
                    *p_v11 = 0;
                    p_v9 = (char *)(i_v15 + 1);
                }
                if (i_v10 == 0) {
                    // 0x10904
                    if (p_v9 != NULL) {
                        // 0x10910
                        function_1068c();
                    }
                    // 0x1094c
                    function_1062c();
                }
                // 0x10960
                i_v7 = function_1062c();
            }
            // 0x10998
            i_v14 = i_v10 + 1;
            p_v5 = p_v8;
            while (p_v8 != NULL) {
                // 0x10880
                i_v10 = i_v14;
                i_v12 = function_106a4();
                p_v13 = (char *)i_v12;
                p_v8 = p_v13;
                if (i_v12 != 0) {
                    // 0x108a0
                    *p_v13 = 0;
                    p_v8 = (char *)(i_v12 + 1);
                }
                // 0x108b4
                i_v7 = i_v12;
                if (*p_v5 != 0) {
                    // 0x108c4
                    i_v15 = function_106a4();
                    p_v11 = (char *)i_v15;
                    p_v9 = p_v11;
                    if (i_v15 != 0) {
                        // 0x108e4
                        *p_v11 = 0;
                        p_v9 = (char *)(i_v15 + 1);
                    }
                    if (i_v10 == 0) {
                        // 0x10904
                        if (p_v9 != NULL) {
                            // 0x10910
                            function_1068c();
                        }
                        // 0x1094c
                        function_1062c();
                    }
                    // 0x10960
                    i_v7 = function_1062c();
                }
                // 0x10998
                i_v14 = i_v10 + 1;
                p_v5 = p_v8;
            }
            // 0x109b8
            i_v6 = i_v7;
            if (i_v14 >= 1) {
                // 0x109c4
                i_v6 = function_10650();
            }
        }
        // 0x109d0
        i_v16 = (int32_t)p_v3;
    }
    // 0x109e4
    return i_v6;
}

// Address range: 0x109ec - 0x10dec
int32_t function_109ec(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x109ec
    if (function_106ec() == 0) {
        // 0x10a30
        function_1062c();
        // 0x10de0
        return 1;
    }
    // 0x10a48
    if (function_106e0() == -1) {
        // 0x10a68
        function_106bc();
        function_10674();
        function_1062c();
        // 0x10de0
        return 1;
    }
    // 0x10a98
    function_106c8();
    function_10638();
    if (function_10728() < 0) {
        // 0x10afc
        function_106bc();
        function_10674();
        function_1062c();
        // 0x10de0
        return 1;
    }
    // 0x10b2c
    function_10620();
    function_10620();
    function_10620();
    function_10620();
    function_10620();
    function_10698();
    int32_t i_v1; // 0x109ec
    if (function_1071c() < 0) {
        // 0x10c10
        function_106bc();
        function_10674();
        function_1062c();
        i_v1 = 1;
    lab_0x10dd4:
        // 0x10dd4
        function_10710();
        // 0x10de0
        return i_v1;
    }
    int32_t i_v2 = function_1065c(); // 0x10c58
    int32_t i_v3 = i_v2;             // 0x10c6c
    int32_t i_v4 = 0xffff;           // 0x10c6c
    int32_t i_v5 = 0;                // 0x10c6c
    if (i_v2 == 0) {
        // 0x10c70
        function_1062c();
        // 0x10de0
        return 1;
    }
    int32_t i_v6; // 0x109ec
    int32_t i_v7; // 0x109ec
    while (true) {
        // 0x10c98
        i_v7 = i_v5;
        int32_t i_v8 = i_v4;
        int32_t i_v9 = i_v3; // 0x10ca4
        i_v4 = i_v8;
        if (i_v8 == i_v7) {
            // 0x10ca8
            i_v9 = function_10644();
            i_v4 = i_v8 + 0xffff;
            if (i_v9 == 0) {
                // break -> 0x10cdc
                break;
            }
        }
        // 0x10cfc
        i_v3 = i_v9;
        int32_t i_v10 = function_10704(); // 0x10d1c
        if (i_v10 < 0) {
            // 0x10d30
            function_106bc();
            function_10674();
            function_1062c();
            i_v6 = 1;
            goto lab_0x10d88;
        }
        // 0x10d64
        i_v5 = i_v10 + i_v7;
        i_v6 = 0;
        if (i_v10 == 0) {
            goto lab_0x10d88;
        }
    }
    // 0x10cdc
    function_1062c();
    // 0x10de0
    return 1;
lab_0x10d88:
    // 0x10d88
    *(char *)(i_v3 + i_v7) = 0;
    if (i_g3 == 0) {
        // 0x10dbc
        function_1062c();
        function_10814(i_v3);
        i_v1 = i_v6;
        goto lab_0x10dd4;
    } else {
        // 0x10db0
        function_10650();
        i_v1 = i_v6;
        goto lab_0x10dd4;
    }
}

// Address range: 0x10dec - 0x10eac
int32_t function_10dec(int32_t i_a1) {
    uint32_t i_v1 = i_a1;
    int32_t i_v2 = *(int32_t *)function_1068c();                      // 0x10e14
    int16_t i_v3 = *(int16_t *)(2 * (int32_t) * (char *)i_v1 + i_v2); // 0x10e28
    int32_t i_v4 = i_v1 + 1;                                          // 0x10e34
    while ((i_v3 & 0x2000) != 0) {
        // 0x10e0c
        i_v1 = i_v4;
        i_v2 = *(int32_t *)function_1068c();
        i_v3 = *(int16_t *)(2 * (int32_t) * (char *)i_v1 + i_v2);
        i_v4 = i_v1 + 1;
    }
    int32_t i_v5 = function_106a4(); // 0x10e40
    if (i_v1 <= i_v5 != i_v1 != i_v5) {
        // 0x10e9c
        return i_v1;
    }
    int32_t i_v6 = i_v5; // 0x10e98
    i_v6--;
    char *p_v7 = (char *)i_v6;
    int32_t i_v8 = *(int32_t *)function_1068c(); // 0x10e54
    if ((*(int16_t *)(2 * (int32_t)*p_v7 + i_v8) & 0x2000) != 0) {
        // 0x10e78
        *p_v7 = 0;
    }
    while (i_v1 <= i_v6 == (i_v1 != i_v6)) {
        // 0x10e4c
        i_v6--;
        p_v7 = (char *)i_v6;
        i_v8 = *(int32_t *)function_1068c();
        if ((*(int16_t *)(2 * (int32_t)*p_v7 + i_v8) & 0x2000) != 0) {
            // 0x10e78
            *p_v7 = 0;
        }
    }
    // 0x10e9c
    return i_v1;
}

// Address range: 0x10eac - 0x110f8
int32_t function_10eac(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = 1; // 0x10ef0
    if (i_a1 >= 2) {
        // 0x10ef4
        if (function_10614() == 0 || function_10614() == 0 ||
            function_10614() == 0) {
            // 0x10f6c
            function_106b0();
            // 0x110ec
            return 1;
        }
        // 0x10fa4
        i_v1 = 1;
        if (function_10614() == 0) {
            // 0x10fcc
            i_g3 = 1;
            i_v1 = 2;
        }
    }
    char *p_v2 = "summary"; // 0x10ff0
    int32_t i_v3 = i_v1;    // 0x10ff0
    if (i_v1 < i_a1) {
        char *p_v4 =
            (char *)function_10dec(*(int32_t *)(4 * i_v1 + i_a2)); // 0x11020
        p_v2 = *p_v4 == 0 ? "summary" : p_v4;
        i_v3 = i_v1 + 1;
    }
    char *p_v5 = "127.0.0.1"; // 0x11040
    int32_t i_v6 = i_v3;      // 0x11040
    if (i_v3 < i_a1) {
        char *p_v7 =
            (char *)function_10dec(*(int32_t *)(4 * i_v3 + i_a2)); // 0x11070
        p_v5 = *p_v7 == 0 ? "127.0.0.1" : p_v7;
        i_v6 = i_v3 + 1;
    }
    int32_t i_v8 = 4028; // 0x11090
    if (i_v6 < i_a1) {
        int32_t i_v9 = function_10dec(*(int32_t *)(4 * i_v6 + i_a2)); // 0x110ac
        i_v8 = 4028;
        if (*(char *)i_v9 != 0) {
            // 0x110c4
            i_v8 = 0x10000 * function_106d4() >> 16;
        }
    }
    // 0x110ec
    return function_109ec((int32_t)p_v2, (int32_t)p_v5, i_v8);
}

// Address range: 0x110f8 - 0x11130
int32_t function_110f8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_105f4(i_a1, i_a2, i_a3, i_a4); // 0x1110a
    return (int32_t)&i_g1 - 0x15880 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x1113c - 0x11144
int32_t function_1113c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x1113c
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 42
