//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_1051c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_1053c(void);
int32_t function_10548(void);
int32_t function_10554(void);
int32_t function_10560(void);
int32_t function_1056c(void);
int32_t function_10578(void);
int32_t function_10584(void);
int32_t function_10590(void);
int32_t function_1059c(void);
int32_t function_105a8(void);
int32_t function_105b4(void);
int32_t function_105c0(void);
int32_t function_105cc(void);
int32_t function_105d8(void);
int32_t function_105e4(void);
int32_t function_105f0(void);
int32_t function_105fc(void);
int32_t function_10608(void);
int32_t function_10614(int32_t i_a1, int32_t i_a2);
int32_t function_10894(void);
int32_t function_108b8(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_108e2(int32_t i_a1, int32_t i_a2);
int32_t function_10908(void);
int32_t function_10920(void);
int32_t function_10944(void);
int32_t function_10964(void);
int32_t function_1097c(void);
int32_t function_10a6c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10aa8(void);
int32_t function_10aac(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x2160002; // 0x10496
int32_t i_g2 = 0x10921;   // 0x20f10
int32_t i_g3 = 0;         // 0x21054
char *p_g4;               // 0x21060

// ------------------------ Functions -------------------------

// Address range: 0x1051c - 0x10528
int32_t function_1051c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x1051c
    return function_10894();
}

// Address range: 0x1053c - 0x10548
int32_t function_1053c(void) {
    // 0x1053c
    int32_t i_v1; // 0x1053c
    return i_v1;
}

// Address range: 0x10548 - 0x10554
int32_t function_10548(void) {
    // 0x10548
    int32_t i_v1; // 0x10548
    return i_v1;
}

// Address range: 0x10554 - 0x10560
int32_t function_10554(void) {
    // 0x10554
    int32_t i_v1; // 0x10554
    return i_v1;
}

// Address range: 0x10560 - 0x1056c
int32_t function_10560(void) {
    // 0x10560
    int32_t i_v1; // 0x10560
    return i_v1;
}

// Address range: 0x1056c - 0x10578
int32_t function_1056c(void) {
    // 0x1056c
    int32_t i_v1; // 0x1056c
    return i_v1;
}

// Address range: 0x10578 - 0x10584
int32_t function_10578(void) {
    // 0x10578
    int32_t i_v1; // 0x10578
    return i_v1;
}

// Address range: 0x10584 - 0x10590
int32_t function_10584(void) {
    // 0x10584
    int32_t i_v1; // 0x10584
    return i_v1;
}

// Address range: 0x10590 - 0x1059c
int32_t function_10590(void) {
    // 0x10590
    int32_t i_v1; // 0x10590
    return i_v1;
}

// Address range: 0x1059c - 0x105a8
int32_t function_1059c(void) {
    // 0x1059c
    int32_t i_v1; // 0x1059c
    return i_v1;
}

// Address range: 0x105a8 - 0x105b4
int32_t function_105a8(void) {
    // 0x105a8
    int32_t i_v1; // 0x105a8
    return i_v1;
}

// Address range: 0x105b4 - 0x105c0
int32_t function_105b4(void) {
    // 0x105b4
    int32_t i_v1; // 0x105b4
    return i_v1;
}

// Address range: 0x105c0 - 0x105cc
int32_t function_105c0(void) {
    // 0x105c0
    int32_t i_v1; // 0x105c0
    return i_v1;
}

// Address range: 0x105cc - 0x105d8
int32_t function_105cc(void) {
    // 0x105cc
    int32_t i_v1; // 0x105cc
    return i_v1;
}

// Address range: 0x105d8 - 0x105e4
int32_t function_105d8(void) {
    // 0x105d8
    int32_t i_v1; // 0x105d8
    return i_v1;
}

// Address range: 0x105e4 - 0x105f0
int32_t function_105e4(void) {
    // 0x105e4
    int32_t i_v1; // 0x105e4
    return i_v1;
}

// Address range: 0x105f0 - 0x105fc
int32_t function_105f0(void) {
    // 0x105f0
    int32_t i_v1; // 0x105f0
    return i_v1;
}

// Address range: 0x105fc - 0x10608
int32_t function_105fc(void) {
    // 0x105fc
    int32_t i_v1; // 0x105fc
    return i_v1;
}

// Address range: 0x10608 - 0x10614
int32_t function_10608(void) {
    // 0x10608
    int32_t i_v1; // 0x10608
    return i_v1;
}

// Address range: 0x10614 - 0x10864
int32_t function_10614(int32_t i_a1, int32_t i_a2) {
    // 0x10614
    function_1053c();
    while (true) {
        // 0x10660
        if (function_1097c() == 0) {
            while (true) {
                // 0x10670
                function_10590();
                function_105b4();
                function_105b4();
                function_1059c();
                if (function_1097c() != 1) {
                    while (true) {
                    lab_generated_0:
                        function_10590();
                        // 0x10804
                        function_10584();
                        goto lab_0x1069c;
                    }
                }
            lab_0x107d0_2:
                // 0x107d0
                function_105b4();
                function_105b4();
                if (function_1097c() != 0) {
                    // break -> 0x107f8
                    break;
                }
            }
        }
        // 0x107f8
        function_10560();
    }
lab_0x10820:
    // 0x10820
    function_105b4();
    function_105b4();
    if (i_a1 < 2) {
        // 0x10858
        function_10560();
        // 0x10850
        function_105cc();
        // 0x10858
        function_10560();
        goto lab_0x10850;
    } else {
        // 0x10844
        function_10554();
        // 0x10850
        function_105cc();
        // 0x10858
        function_10560();
        goto lab_0x10850;
    }
lab_0x1069c:
    // 0x1069c
    if (function_1097c() == 1) {
        // break -> 0x107d0
        goto lab_0x107d0_2;
    }
    goto lab_generated_1;
}

// Address range: 0x10864 - 0x1088c
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10864
    function_105a8();
    return function_10608();
}

// Address range: 0x10894 - 0x108b0
int32_t function_10894(void) {
    // 0x10894
    if (i_g3 == 0) {
        int32_t i_v1; // 0x10894
        return i_v1;
    }
    // 0x108ac
    return function_105c0();
}

// Address range: 0x108b8 - 0x108e0
int32_t function_108b8(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x108b8
    bool i_v1; // 0x108b8
    if (!i_v1 && false) {
        __asm_svclt(0x4770);
    }
    return i_a1;
}

// Address range: 0x108e2 - 0x10906
int32_t function_108e2(int32_t i_a1, int32_t i_a2) {
    // 0x108e2
    int32_t i_v1; // 0x108e2
    return 32 * i_v1 | 0x20000;
}

// Address range: 0x10908 - 0x10920
int32_t function_10908(void) {
    // 0x10908
    int32_t i_v1; // 0x10908
    if (*(char *)&p_g4 == 0) {
        // 0x10916
        int32_t i_v2;                                       // 0x10908
        int32_t i_v3 = function_108b8(i_v2, i_v2, i_v2, 0); // 0x10916
        *(char *)&p_g4 = 1;
        i_v1 = i_v3;
    }
    // 0x1091e
    return i_v1;
}

// Address range: 0x10920 - 0x10944
int32_t function_10920(void) {
    function_105b4();
    return function_105b4();
}

// Address range: 0x10944 - 0x10964
int32_t function_10944(void) {
    // 0x10944
    function_105b4();
    return function_105b4();
}

// Address range: 0x10964 - 0x1097c
int32_t function_10964(void) {
    // 0x10964
    function_105d8();
    return 0;
}

// Address range: 0x1097c - 0x10a6c
int32_t function_1097c(void) {
    int32_t i_v1 = function_105d8(); // 0x10990
    int32_t i_v2 = function_105fc();
    if (i_v1 == 0) {
        int32_t i_v3; // 0x1097c
        if (i_v2 == 0) {
            // 0x10a58
            function_1059c();
            i_v3 = -1;
        } else {
            // 0x10a14
            function_10548();
            function_105e4();
            int32_t i_v4; // 0x1097c
            i_v3 = i_v4 != 0;
        }
        // 0x10a38
        return i_v3;
    }
    if (i_v2 == 0) {
        // 0x10a40
        function_1059c();
        return -1;
    }
    // 0x109b8
    if (function_10578() != 1) {
        // 0x109d8
        function_1059c();
    }
    // 0x109e4
    function_105e4();
    return -1;
}

// Address range: 0x10a6c - 0x10aa0
int32_t function_10a6c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_1051c(i_a1, i_a2, i_a3, i_a4); // 0x10a7c
    int32_t i_v2 =
        (int32_t)&i_g1 + 0x10a7c - (int32_t)&i_g2 >> 2 == 0 ? i_v1 : i_a1;
    return i_v2;
}

// Address range: 0x10aa8 - 0x10aaa
int32_t function_10aa8(void) {
    // 0x10aa8
    int32_t i_v1; // 0x10aa8
    return i_v1;
}

// Address range: 0x10aac - 0x10ab4
int32_t function_10aac(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10aac
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 32
