//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_10510(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10530(void);
int32_t function_1053c(void);
int32_t function_10548(void);
int32_t function_10554(void);
int32_t function_10560(void);
int32_t function_1056c(void);
int32_t function_10578(void);
int32_t function_10584(void);
int32_t function_10590(void);
int32_t function_1059c(void);
int32_t function_105a8(void);
int32_t function_105b4(void);
int32_t function_105c0(void);
int32_t function_105cc(void);
int32_t function_105d8(void);
int32_t function_105e4(void);
int32_t function_105f0(int32_t i_a1, int32_t i_a2);
int32_t function_10950(void);
int32_t function_10974(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_109c8(int32_t i_a1);
int32_t function_109dc(void);
int32_t function_109e0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10a1c(void);
int32_t function_10a20(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = -0x1cae0000; // 0x10960
int32_t i_g2 = 0x109dd;     // 0x20f10

// ------------------------ Functions -------------------------

// Address range: 0x10510 - 0x1051c
int32_t function_10510(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10510
    return function_10950();
}

// Address range: 0x10530 - 0x1053c
int32_t function_10530(void) {
    // 0x10530
    int32_t i_v1; // 0x10530
    return i_v1;
}

// Address range: 0x1053c - 0x10548
int32_t function_1053c(void) {
    // 0x1053c
    int32_t i_v1; // 0x1053c
    return i_v1;
}

// Address range: 0x10548 - 0x10554
int32_t function_10548(void) {
    // 0x10548
    int32_t i_v1; // 0x10548
    return i_v1;
}

// Address range: 0x10554 - 0x10560
int32_t function_10554(void) {
    // 0x10554
    int32_t i_v1; // 0x10554
    return i_v1;
}

// Address range: 0x10560 - 0x1056c
int32_t function_10560(void) {
    // 0x10560
    int32_t i_v1; // 0x10560
    return i_v1;
}

// Address range: 0x1056c - 0x10578
int32_t function_1056c(void) {
    // 0x1056c
    int32_t i_v1; // 0x1056c
    return i_v1;
}

// Address range: 0x10578 - 0x10584
int32_t function_10578(void) {
    // 0x10578
    int32_t i_v1; // 0x10578
    return i_v1;
}

// Address range: 0x10584 - 0x10590
int32_t function_10584(void) {
    // 0x10584
    int32_t i_v1; // 0x10584
    return i_v1;
}

// Address range: 0x10590 - 0x1059c
int32_t function_10590(void) {
    // 0x10590
    int32_t i_v1; // 0x10590
    return i_v1;
}

// Address range: 0x1059c - 0x105a8
int32_t function_1059c(void) {
    // 0x1059c
    int32_t i_v1; // 0x1059c
    return i_v1;
}

// Address range: 0x105a8 - 0x105b4
int32_t function_105a8(void) {
    // 0x105a8
    int32_t i_v1; // 0x105a8
    return i_v1;
}

// Address range: 0x105b4 - 0x105c0
int32_t function_105b4(void) {
    // 0x105b4
    int32_t i_v1; // 0x105b4
    return i_v1;
}

// Address range: 0x105c0 - 0x105cc
int32_t function_105c0(void) {
    // 0x105c0
    int32_t i_v1; // 0x105c0
    return i_v1;
}

// Address range: 0x105cc - 0x105d8
int32_t function_105cc(void) {
    // 0x105cc
    int32_t i_v1; // 0x105cc
    return i_v1;
}

// Address range: 0x105d8 - 0x105e4
int32_t function_105d8(void) {
    // 0x105d8
    int32_t i_v1; // 0x105d8
    return i_v1;
}

// Address range: 0x105e4 - 0x105f0
int32_t function_105e4(void) {
    // 0x105e4
    int32_t i_v1; // 0x105e4
    return i_v1;
}

// Address range: 0x105f0 - 0x10920
int32_t function_105f0(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1; // 0x105f0
    int32_t i_v2; // 0x10614
    if (i_a1 < 2) {
        // 0x10824
        function_105b4();
        function_1059c();
        goto lab_0x10848;
    } else {
        // 0x10604
        i_v2 = function_105a8();
        i_v1 = 119;
        if (i_a1 == 2) {
            goto lab_0x1062c;
        } else {
            goto lab_0x10700;
        }
    }
lab_0x10848:
    // 0x10848
    function_105c0();
    function_10578();
    function_105b4();
    function_1059c();
    goto lab_0x10890;
lab_0x1062c:
    // 0x1062c
    if (function_10554() == -1) {
        // 0x108d8
        function_105c0();
        function_10578();
        function_105b4();
        return function_1059c();
    }
    // 0x1064c
    function_10560();
    function_1053c();
    int32_t i_v3 = function_10548(); // 0x10690
    if (i_v3 == -1) {
        goto lab_0x10848;
    } else {
        int32_t i_v4 = __asm_ubfx(i_v2, 0, 12); // 0x106ac
        function_10530();
        function_1053c();
        switch (i_v1) {
        case 104: {
            // 0x107ac
            function_10530();
            function_1053c();
            if (i_a1 < 4) {
                goto lab_0x10740;
            } else {
                // 0x107d0
                *(int16_t *)(i_v4 + i_v3) = (int16_t)function_105a8();
                // 0x107ec
                function_10530();
                function_1053c();
                goto lab_0x10740;
            }
        }
        case 119: {
            // 0x1071c
            function_10530();
            function_1053c();
            if (i_a1 > 3) {
                // 0x10804
                *(int32_t *)(i_v4 + i_v3) = function_105a8();
                // 0x107ec
                function_10530();
                function_1053c();
                goto lab_0x10740;
            } else {
                goto lab_0x10740;
            }
        }
        case 98: {
            // 0x10768
            function_10530();
            function_1053c();
            if (i_a1 < 4) {
                goto lab_0x10740;
            } else {
                // 0x1078c
                *(char *)(i_v4 + i_v3) = (char)function_105a8();
                // 0x107ec
                function_10530();
                function_1053c();
                goto lab_0x10740;
            }
        }
        default: {
            // 0x106dc
            function_105b4();
            function_1059c();
            goto lab_0x10700;
        }
        }
    }
lab_0x10700:;
    int32_t i_v5 = function_10584();                      // 0x10700
    unsigned char i_v6 = *(char *)*(int32_t *)(i_a2 + 8); // 0x1070c
    i_v1 = *(int32_t *)(4 * (int32_t)i_v6 + *(int32_t *)i_v5);
    goto lab_0x1062c;
lab_0x10890:
    // 0x10890
    function_105c0();
    function_10578();
    function_105b4();
    function_1059c();
    // 0x108d8
    function_105c0();
    function_10578();
    function_105b4();
    return function_1059c();
lab_0x10740:
    // 0x10740
    if (function_105cc() != -1) {
        // 0x10754
        function_105e4();
        return 0;
    }
    goto lab_0x10890;
}

// Address range: 0x10920 - 0x10948
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10920
    function_1056c();
    return function_105d8();
}

// Address range: 0x10950 - 0x1096c
int32_t function_10950(void) {
    int32_t i_v1 =
        *(int32_t *)((int32_t)&i_g1 + (int32_t) "0\v" + 76); // 0x1095c
    if (i_v1 == 0) {
        int32_t i_v2; // 0x10950
        return i_v2;
    }
    // 0x10968
    return function_10590();
}

// Address range: 0x10974 - 0x109c8
int32_t function_10974(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x10974
    int32_t i_v1; // 0x10974
    int32_t i_v2 = i_v1;
    bool i_v3; // 0x10974
    if (i_v3) {
        return i_a1;
    }
    if (i_v1 < i_v1) {
        __asm_svclt(0x4770);
    }
    bool i_v4; // 0x10974
    if (!i_v3) {
        int32_t i_v5 = 0x100001 * i_v2 & -1 - 0x400000 * i_v2; // 0x109ac
        i_v4 = i_v5 < 0;
        if (i_v5 == 0) {
            return unknown_240();
        }
    }
    // 0x109bc
    if (i_v4 != i_v3) {
        __asm_svclt(0x4770);
    }
    float64_t f_v6; // 0x10974
    __asm_vqrshl_s8(f_v6, f_v6);
    return i_a1;
}

// Address range: 0x109c8 - 0x109dc
int32_t function_109c8(int32_t i_a1) {
    // 0x109c8
    int32_t i_v1;                          // 0x109c8
    int32_t i_v2 = 0x20000 * i_v1;         // 0x109c8
    char *p_v3 = (char *)(i_v1 | 0x20000); // 0x109ce
    int32_t i_v4 = i_v2;                   // 0x109d0
    if (*p_v3 == 0) {
        // 0x109d2
        i_v4 = function_10974(i_v2, i_v1, i_v1, 0);
        *p_v3 = 1;
    }
    // 0x109da
    return i_v4;
}

// Address range: 0x109dc - 0x109de
int32_t function_109dc(void) {
    // 0x109dc
    int32_t i_v1; // 0x109dc
    return i_v1;
}

// Address range: 0x109e0 - 0x10a14
int32_t function_109e0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_10510(i_a1, i_a2, i_a3, i_a4); // 0x109f0
    return 0x20f12 - (int32_t)&i_g2 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x10a1c - 0x10a1e
int32_t function_10a1c(void) {
    // 0x10a1c
    int32_t i_v1; // 0x10a1c
    return i_v1;
}

// Address range: 0x10a20 - 0x10a28
int32_t function_10a20(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10a20
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 26
