#!/bin/sh

NAME=monitor-ipsigTH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/monitor-recobtn
NAME=monitor-recobtn
DESC="Monitor-recobtn daemon"
ARGS="/usr/bin/factory_config_reset.sh"

set -e

test -x "$DAEMON" || exit 0


do_start() {
        start-stop-daemon -b -S -x $DAEMON -- $ARGS
}

do_stop() {
        killall -9 $NAME
}

case "$1" in
  start)
		echo "in zhiju mode,ignore recover function"
		exit 0
        echo -n "Starting $DESC: "
		do_start
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
		do_stop
        echo "$NAME."
        ;;
		  restart|force-reload)
        echo -n "Restarting $DESC: "
        do_stop
        do_start
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

