//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t bitmain_asic_close(void);
int32_t bitmain_asic_ioctl(void);
int32_t bitmain_asic_open(void);
int32_t bitmain_asic_write(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t CheckBusy(void);
int32_t cleanup_module(void);
int32_t enable_gpios(int32_t i_a1, int32_t i_a2);
int32_t function_2c0(void);
int32_t function_2c2(int32_t i_a1);
int32_t function_2cc(int32_t i_a1, int32_t i_a2);
int32_t function_554e47(void);
int32_t function_fffffde8(void);
int32_t hanzi_Disp(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t init_module(void);
int32_t lcd_display_init(void);
int32_t Lcd_Fill(int32_t i_a1);
int32_t lcd_hw_init(void);
int32_t ReceiveByte(void);
int32_t SendByte(int32_t i_a1);
int32_t SendCommad(int32_t i_a1);
int32_t SendData(int32_t i_a1);
int32_t set_cs(int32_t i_a1, int32_t i_a2);
int32_t set_cs_direction(int32_t i_a1, int32_t i_a2);
int32_t set_reset(int32_t i_a1, int32_t i_a2);
int32_t set_reset_direction(int32_t i_a1, int32_t i_a2);
int32_t set_sclk(int32_t i_a1, int32_t i_a2);
int32_t set_sclk_direction(int32_t i_a1, int32_t i_a2);
int32_t set_sid(int32_t i_a1, int32_t i_a2);
int32_t set_sid_direction(int32_t i_a1, int32_t i_a2);
int32_t unknown_1b60(void);
int32_t unknown_1b64(int32_t i_a1);
int32_t unknown_1b6c(int32_t i_a1, int32_t *p_a2);
int32_t unknown_1b70(char *p_a1, int32_t i_a2);
int32_t unknown_1b74(int32_t *p_a1, int32_t *p_a2, int32_t *p_a3);
int32_t unknown_1b78(int32_t *p_a1);
int32_t unknown_1b7c(int32_t *p_a1, int32_t i_a2, int32_t i_a3);

// --------------------- Global Variables ---------------------

char *p_g2;                                               // 0x1
bool i_g3 = false;                                        // 0x10
int32_t i_g4 = 0x3a8dd9b9;                                // 0x14
int32_t i_g5;                                             // 0x1b28
int32_t i_g6;                                             // 0x1b2c
int32_t i_g8 = -0x6e0924c0;                               // 0x20
int32_t i_g9;                                             // 0x3
int32_t i_g11 = -0x1a60fff8;                              // 0x40
int32_t i_g13 = 0x554e4700;                               // 0xb
char *p_g14 = "\x01\x30\x46UNCTION_SETTING\n\n";          // 0xc2a
char *p_g15 = "\x01\x30SET_ENTRY_POINT\n\n";              // 0xc3f
char *p_g16 = "\x01\x30\x44ISPLAY_STATUS\n\n";            // 0xc53
char *p_g17 = "\x01\x30\x43LEAR_DISPLAY\n\n";             // 0xc66
char *p_g18 = "\x01\x30SET_ADDRESS_BACK\n\n";             // 0xc78
char *p_g19 = "\x01\x30SET_DDRAM_ADDRESS\n\n";            // 0xc8d
char *p_g20 = "\x01\x33%s: failed to register device\n";  // 0xcaf
char *p_g21 = "\x01\x33%s: success to register device\n"; // 0xcd0
int32_t i_g22 = 255;                                      // 0xd28
int32_t **p_g1 = &p_g10;                                  // 0x0
int32_t ***p_g7 = &p_g1;                                  // 0x1b30
int32_t *p_g10 = &i_g4;                                   // 0x4
int32_t *p_g12 = &i_g9;                                   // 0x8

// ------------------------ Functions -------------------------

// Address range: 0x24 - 0x38
int32_t bitmain_asic_close(void) {
    // 0x24
    int32_t i_v1; // 0x24
    unknown_1b70("bitmain lcd closed!\n", i_v1);
    return 0;
}

// Address range: 0x3c - 0x50
int32_t bitmain_asic_open(void) {
    // 0x3c
    int32_t i_v1; // 0x3c
    unknown_1b70("bitmain lcd opened!\n", i_v1);
    return 0;
}

// Address range: 0x54 - 0x68
int32_t bitmain_asic_ioctl(void) {
    // 0x54
    int32_t i_v1; // 0x54
    unknown_1b70("bitmain lcd ioctl is not supported!\n", i_v1);
    return 0;
}

// Address range: 0x6c - 0xb8
int32_t set_cs_direction(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = i_g5;            // 0x78
    int32_t i_v2 = __asm_dsb(i_a1); // 0x7c
    __asm_dsb(i_v2);
    int32_t i_v3 = unknown_1b60(); // 0xa0
    *(int32_t *)i_g5 = i_v2 == 0 ? i_v1 & -0x10001 : i_v1 | 0x10000;
    return i_v3;
}

// Address range: 0xbc - 0x108
int32_t set_sclk_direction(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = i_g5;            // 0xc8
    int32_t i_v2 = __asm_dsb(i_a1); // 0xcc
    __asm_dsb(i_v2);
    int32_t i_v3 = unknown_1b60(); // 0xf0
    *(int32_t *)i_g5 = i_v2 == 0 ? i_v1 & -0x100001 : i_v1 | 0x100000;
    return i_v3;
}

// Address range: 0x10c - 0x158
int32_t set_sid_direction(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = i_g5;            // 0x118
    int32_t i_v2 = __asm_dsb(i_a1); // 0x11c
    __asm_dsb(i_v2);
    int32_t i_v3 = unknown_1b60(); // 0x140
    *(int32_t *)i_g5 = i_v2 == 0 ? i_v1 & -0x20001 : i_v1 | 0x20000;
    return i_v3;
}

// Address range: 0x15c - 0x1a8
int32_t set_reset_direction(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = i_g5;            // 0x168
    int32_t i_v2 = __asm_dsb(i_a1); // 0x16c
    __asm_dsb(i_v2);
    int32_t i_v3 = unknown_1b60(); // 0x190
    *(int32_t *)i_g5 = i_v2 == 0 ? i_v1 & -0x200001 : i_v1 | 0x200000;
    return i_v3;
}

// Address range: 0x1ac - 0x1f8
int32_t set_cs(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = *(int32_t *)*(int32_t *)((int32_t)&i_g5 + 4); // 0x1b8
    int32_t i_v2 = __asm_dsb(i_a1);                              // 0x1bc
    __asm_dsb(i_v2);
    int32_t i_v3 = unknown_1b60(); // 0x1e0
    *(int32_t *)i_g6 = i_v2 == 0 ? i_v1 & -0x10001 : i_v1 | 0x10000;
    return i_v3;
}

// Address range: 0x1fc - 0x248
int32_t set_sclk(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = i_g6;            // 0x208
    int32_t i_v2 = __asm_dsb(i_a1); // 0x20c
    __asm_dsb(i_v2);
    int32_t i_v3 = unknown_1b60(); // 0x230
    *(int32_t *)i_g6 = i_v2 == 0 ? i_v1 & -0x100001 : i_v1 | 0x100000;
    return i_v3;
}

// Address range: 0x24c - 0x298
int32_t set_sid(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = i_g6;            // 0x258
    int32_t i_v2 = __asm_dsb(i_a1); // 0x25c
    __asm_dsb(i_v2);
    int32_t i_v3 = unknown_1b60(); // 0x280
    *(int32_t *)i_g6 = i_v2 == 0 ? i_v1 & -0x20001 : i_v1 | 0x20000;
    return i_v3;
}

// Address range: 0x29c - 0x2c0
int32_t set_reset(int32_t i_a1, int32_t i_a2) {
    // 0x29c
    return __asm_dsb(i_a1);
}

// Address range: 0x2c0 - 0x2c1
int32_t function_2c0(void) {
    // 0x2c0
    int32_t i_v1; // 0x2c0
    return i_v1;
}

// Address range: 0x2c2 - 0x2cc
int32_t function_2c2(int32_t i_a1) {
    // 0x2c2
    return function_fffffde8();
}

// Address range: 0x2cc - 0x2e8
int32_t function_2cc(int32_t i_a1, int32_t i_a2) {
    // 0x2cc
    int32_t i_v1; // 0x2cc
    __asm_dsb(i_v1);
    unknown_1b60();
    *(int32_t *)*(int32_t *)(i_v1 + (int32_t)&p_g10) = i_a1;
    return function_554e47();
}

// Address range: 0x2ec - 0x334
int32_t enable_gpios(int32_t i_a1, int32_t i_a2) {
    // 0x2ec
    __asm_dsb(__asm_dsb(i_a1));
    int32_t i_v1 = unknown_1b60(); // 0x31c
    *(int32_t *)p_g7 = (int32_t)p_g7 | 0x330000;
    return i_v1;
}

// Address range: 0x338 - 0x398
int32_t SendByte(int32_t i_a1) {
    uint32_t i_v1 = 0;
    int32_t i_v2 = i_v1 + (int32_t)&p_g2; // 0x358
    __asm_ubfx(i_a1 << i_v1, 7, 1);
    while (i_v2 != (int32_t)&p_g12) {
        // 0x34c
        i_v1 = i_v2;
        i_v2 = i_v1 + (int32_t)&p_g2;
        __asm_ubfx(i_a1 << i_v1, 7, 1);
    }
    // 0x394
    return 0;
}

// Address range: 0x3a0 - 0x4ac
int32_t ReceiveByte(void) {
    uint32_t i_v1 = 0;
    __asm_dsb(0);
    int32_t i_v2 = __asm_ubfx(i_g6, 25, 1);       // 0x400
    int32_t i_v3 = i_v1 + (int32_t)&p_g2;         // 0x410
    uint32_t i_v4 = __asm_sxtb(i_v2 | 0 << i_v1); // 0x414
    int32_t i_v5 = i_v4 % 256;                    // 0x424
    int32_t i_v6 = 0;                             // 0x424
    int32_t i_v7 = 0;                             // 0x424
    while (i_v3 != (int32_t)&p_g12) {
        // 0x3c0
        i_v1 = i_v3;
        __asm_dsb(0);
        i_v2 = __asm_ubfx(i_g6, 25, 1);
        i_v3 = i_v1 + (int32_t)&p_g2;
        i_v4 = __asm_sxtb(i_v2 | i_v5 << i_v1);
        i_v5 = i_v4 % 256;
        i_v6 = 0;
        i_v7 = 0;
    }
    int32_t i_v8 = __asm_ubfx(__asm_dsb(i_g6), 25, 1); // 0x470
    int32_t i_v9 = i_v6 + (int32_t)&p_g2;              // 0x47c
    uint32_t i_v10 = (i_v8 | i_v7 << i_v6) % 256;      // 0x480
    i_v6 = i_v9;
    i_v7 = i_v10;
    while (i_v9 != (int32_t)&p_g12) {
        // 0x434
        i_v8 = __asm_ubfx(__asm_dsb(i_g6), 25, 1);
        i_v9 = i_v6 + (int32_t)&p_g2;
        i_v10 = (i_v8 | i_v7 << i_v6) % 256;
        i_v6 = i_v9;
        i_v7 = i_v10;
    }
    // 0x494
    return i_v10 / 16 | i_v4 & 240;
}

// Address range: 0x4b8 - 0x4d4
int32_t CheckBusy(void) {
    while (true) {
        // continue -> 0x4bc
    }
}

// Address range: 0x4d4 - 0x510
int32_t SendCommad(int32_t i_a1) {
    while (true) {
        // continue -> 0x50c
    }
}

// Address range: 0x510 - 0x54c
int32_t SendData(int32_t i_a1) {
    while (true) {
        // continue -> 0x548
    }
}

// Address range: 0x54c - 0x640
int32_t bitmain_asic_write(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x54c
    int32_t i_v1; // 0x54c
    int32_t i_v2 = i_v1;
    int32_t i_v3; // bp-100, 0x54c
    unknown_1b74(&i_v3, &i_g8, &i_g11);
    int32_t i_v4 = -14;  // 0x57c
    int32_t i_v5 = i_a2; // 0x57c
    if (i_a3 == (int32_t)&i_g11 || i_a3 < (int32_t)&i_g11) {
        goto lab_0x598;
    } else {
        goto lab_0x584;
    }
lab_0x598:;
    // 0x598
    int32_t i_v6; // 0x54c
    int32_t i_v7 = i_v6;
    int32_t i_v8 = i_v5;
    uint32_t i_v9 = i_v8 + i_a3; // 0x5a8
    bool i_v10 = true;           // 0x5ac
    if (i_v9 >= i_v8) {
        i_v10 = !((i_v2 != -1 | i_v9 < -2 - i_v2 + i_v9));
    }
    int32_t i_v11 = i_a3; // 0x5bc
    if (i_v2 == 0 || !i_v10) {
        // 0x5c0
        __asm_mrc(15, 0, i_v7, 3, 0, 0);
        __asm_mcr(15, 0, i_v7 & -13 | (int32_t)&p_g10, 3, 0, 0);
        __asm_isb();
        unknown_1b7c(&i_v3, i_v8, i_a3);
        __asm_mcr(15, 0, i_v7, 3, 0, 0);
        i_v11 = __asm_isb();
    }
    // 0x5ec
    i_v5 = i_v8;
    int32_t i_v12 = i_v7; // 0x5f0
    i_v4 = -14;
    if (i_v11 == 0) {
        int32_t i_v13 = 0;     // 0x5fc
        int32_t i_v14 = &i_v3; // 0x5fc
        int32_t i_v15 = 0;     // 0x608
        while (i_v15 + (int32_t)&p_g2 != (int32_t)&i_g3) {
            // 0x60c
            i_v15 += (int32_t)&p_g2;
        }
        // 0x620
        i_v13 += (int32_t)&p_g2;
        i_v14 += (int32_t)&i_g3;
        i_v5 = (int32_t)&p_g10;
        i_v12 = i_v14;
        i_v4 = i_a3;
        while (i_v13 != (int32_t)&p_g10) {
            // 0x600
            i_v15 = 0;
            while (i_v15 + (int32_t)&p_g2 != (int32_t)&i_g3) {
                // 0x60c
                i_v15 += (int32_t)&p_g2;
            }
            // 0x620
            i_v13 += (int32_t)&p_g2;
            i_v14 += (int32_t)&i_g3;
            i_v5 = (int32_t)&p_g10;
            i_v12 = i_v14;
            i_v4 = i_a3;
        }
    }
    goto lab_0x584;
lab_0x584:;
    int32_t i_v16 = i_v4;
    // 0x638
    return i_v16;
    // 0x594
    unknown_1b64(i_v16);
    i_v6 = i_v12;
    goto lab_0x598;
}

// Address range: 0x648 - 0x83c
int32_t lcd_hw_init(void) {
    // 0x648
    function_2c0();
    function_2c0();
    int32_t i_v1 = &i_g13;
    while (i_v1 != (int32_t)&p_g2) {
        // 0x6d4
        i_v1 -= (int32_t)&p_g2;
    }
    // 0x6dc
    int32_t i_v2; // 0x648
    unknown_1b70((char *)&p_g14, i_v2);
    int32_t i_v3 = &i_g13; // 0x6f4
    while (i_v3 != (int32_t)&p_g2) {
        // 0x6f8
        i_v3 -= (int32_t)&p_g2;
    }
    // 0x700
    unknown_1b70((char *)&p_g15, i_v2);
    int32_t i_v4 = &i_g13; // 0x718
    while (i_v4 != (int32_t)&p_g2) {
        // 0x71c
        i_v4 -= (int32_t)&p_g2;
    }
    // 0x724
    unknown_1b70((char *)&p_g16, i_v2);
    int32_t i_v5 = &i_g13; // 0x73c
    while (i_v5 != (int32_t)&p_g2) {
        // 0x740
        i_v5 -= (int32_t)&p_g2;
    }
    // 0x748
    unknown_1b70((char *)&p_g17, i_v2);
    int32_t i_v6 = &i_g13; // 0x760
    while (i_v6 != (int32_t)&p_g2) {
        // 0x764
        i_v6 -= (int32_t)&p_g2;
    }
    // 0x76c
    unknown_1b70((char *)&p_g18, i_v2);
    int32_t i_v7 = &i_g13; // 0x784
    while (i_v7 != (int32_t)&p_g2) {
        // 0x788
        i_v7 -= (int32_t)&p_g2;
    }
    int32_t i_v8 = unknown_1b70((char *)&p_g19, i_v2);
    int32_t i_v9 = 101;
    int32_t i_v10 = i_v9 - 1; // 0x7a8
    while (i_v9 != 1) {
        // 0x7a4
        i_v8 = 0xccccb60;
        i_v9 = i_v10;
        i_v10 = i_v9 - 1;
    }
    return i_v8;
}

// Address range: 0x85c - 0x954
int32_t lcd_display_init(void) {
    int32_t i_v1 = &i_g13; // 0x870
    while (i_v1 != (int32_t)&p_g2) {
        // 0x874
        i_v1 -= (int32_t)&p_g2;
    }
    // 0x87c
    int32_t i_v2; // 0x85c
    unknown_1b70((char *)&p_g14, i_v2);
    int32_t i_v3 = &i_g13; // 0x894
    while (i_v3 != (int32_t)&p_g2) {
        // 0x898
        i_v3 -= (int32_t)&p_g2;
    }
    // 0x8a0
    unknown_1b70((char *)&p_g14, i_v2);
    int32_t i_v4 = &i_g13; // 0x8b8
    while (i_v4 != (int32_t)&p_g2) {
        // 0x8bc
        i_v4 -= (int32_t)&p_g2;
    }
    // 0x8c4
    unknown_1b70((char *)&p_g16, i_v2);
    int32_t i_v5 = &i_g13; // 0x8dc
    while (i_v5 != (int32_t)&p_g2) {
        // 0x8e0
        i_v5 -= (int32_t)&p_g2;
    }
    int32_t i_v6 = unknown_1b70((char *)&p_g17, i_v2);
    int32_t i_v7 = 101;
    int32_t i_v8 = i_v7 - 1; // 0x900
    while (i_v7 != 1) {
        // 0x8fc
        i_v6 = 0xccccb60;
        i_v7 = i_v8;
        i_v8 = i_v7 - 1;
    }
    return i_v6;
}

// Address range: 0x968 - 0x998
int32_t hanzi_Disp(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    int32_t i_v1 = i_a3 - (int32_t)&p_g2; // 0x980
    while (*(char *)(i_v1 + (int32_t)&p_g2) != 0) {
        // 0x984
        i_v1 += (int32_t)&p_g2;
    }
    return 0;
}

// Address range: 0x99c - 0xa28
int32_t Lcd_Fill(int32_t i_a1) {
    int32_t i_v1 = 128;  // 0x9a8
    int32_t i_v2 = 136;  // 0x9a8
    int32_t i_v3 = 128;  // 0x9b0
    int32_t i_v4 = i_v1; // 0xa08
    while (i_v2 != (i_v4 + 1) % 256) {
        // 0x9b4
        i_v4 = (i_v4 + 1) % 256;
    }
    while ((i_v3 + 1) % 256 != 160) {
        // 0x9f4
        i_v3 = (i_v3 + 1) % 256;
        i_v4 = i_v1;
        while (i_v2 != (i_v4 + 1) % 256) {
            // 0x9b4
            i_v4 = (i_v4 + 1) % 256;
        }
    }
    // 0xa0c
    i_v1 = (i_v1 + 8) % 256;
    i_v2 = (i_v2 + 8) % 256;
    while (i_v1 != 144) {
        // 0x9ac
        i_v3 = 128;
        i_v4 = i_v1;
        while (i_v2 != (i_v4 + 1) % 256) {
            // 0x9b4
            i_v4 = (i_v4 + 1) % 256;
        }
        while ((i_v3 + 1) % 256 != 160) {
            // 0x9f4
            i_v3 = (i_v3 + 1) % 256;
            i_v4 = i_v1;
            while (i_v2 != (i_v4 + 1) % 256) {
                // 0x9b4
                i_v4 = (i_v4 + 1) % 256;
            }
        }
        // 0xa0c
        i_v1 = (i_v1 + 8) % 256;
        i_v2 = (i_v2 + 8) % 256;
    }
    // 0xa24
    return 48;
}

// Address range: 0xa28 - 0xa98
int32_t init_module(void) {
    // 0xa28
    i_g5 = unknown_1b6c(-0x1fff5dbc, (int32_t *)&p_g2);
    i_g6 = unknown_1b6c(-0x1fff5fbc, (int32_t *)&p_g2);
    *(int32_t *)&p_g7 = unknown_1b6c(-0x1fff5db8, (int32_t *)&p_g2);
    int32_t i_v1; // 0xa28
    if (unknown_1b78(&i_g22) == 0) {
        // 0xa8c
        unknown_1b70((char *)&p_g21, (int32_t) "bitmain-lcd");
        i_v1 = 0;
    } else {
        // 0xa78
        unknown_1b70((char *)&p_g20, (int32_t) "bitmain-lcd");
        i_v1 = -1;
    }
    // 0xa84
    return i_v1;
}

// Address range: 0xab8 - 0xac0
int32_t cleanup_module(void) {
    while (true) {
        // continue -> 0xabc
    }
}

// Address range: 0x554e47 - 0x554e48
int32_t function_554e47(void) {
    // 0x554e47
    int32_t i_v1; // 0x554e47
    return i_v1;
}

// Address range: 0xfffffde8 - 0xfffffde9
int32_t function_fffffde8(void) {
    // 0xfffffde8
    int32_t i_v1; // 0xfffffde8
    return i_v1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.2.1)
// Detected functions: 29
