//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_107a4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_107c4(void);
int32_t function_107d0(void);
int32_t function_107dc(void);
int32_t function_107e8(void);
int32_t function_107f4(void);
int32_t function_10800(void);
int32_t function_1080c(void);
int32_t function_10818(void);
int32_t function_10824(void);
int32_t function_10830(void);
int32_t function_1083c(void);
int32_t function_10848(void);
int32_t function_10854(void);
int32_t function_10860(void);
int32_t function_1086c(void);
int32_t function_10878(void);
int32_t function_10884(void);
int32_t function_10890(void);
int32_t function_1089c(void);
int32_t function_108a8(void);
int32_t function_108b4(void);
int32_t function_108c0(void);
int32_t function_108cc(void);
int32_t function_108d8(void);
int32_t function_108e4(void);
int32_t function_108f0(void);
int32_t function_108fc(void);
int32_t function_10908(void);
int32_t function_10914(void);
int32_t function_10920(void);
int32_t function_1092c(void);
int32_t function_10938(int32_t i_a1, int32_t i_a2);
int32_t function_10bac(void);
int32_t function_10bd0(void);
int32_t function_10bf4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10c20(void);
int32_t function_10c38(int32_t i_a1, int32_t i_a2);
int32_t function_10c3e(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10c4a(void);
int32_t function_10c4c(int32_t i_a1);
int32_t function_10c58(void);
int32_t function_10c5c(char *p_a1);
int32_t function_10cac(int32_t i_a1);
int32_t function_10ee0(int32_t i_a1);
int32_t function_11008(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_1104c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t unknown_240(int32_t i_a1);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x10c21; // 0x2169c
int32_t i_g2 = 0;       // 0x2181c
int32_t i_g3 = 0;       // 0x21828
char *p_g4;             // 0x2182c
int32_t i_g5;

// ------------------------ Functions -------------------------

// Address range: 0x107a4 - 0x107b0
int32_t function_107a4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x107a4
    return function_10bac();
}

// Address range: 0x107c4 - 0x107d0
int32_t function_107c4(void) {
    // 0x107c4
    int32_t i_v1; // 0x107c4
    return i_v1;
}

// Address range: 0x107d0 - 0x107dc
int32_t function_107d0(void) {
    // 0x107d0
    int32_t i_v1; // 0x107d0
    return i_v1;
}

// Address range: 0x107dc - 0x107e8
int32_t function_107dc(void) {
    // 0x107dc
    int32_t i_v1; // 0x107dc
    return i_v1;
}

// Address range: 0x107e8 - 0x107f4
int32_t function_107e8(void) {
    // 0x107e8
    int32_t i_v1; // 0x107e8
    return i_v1;
}

// Address range: 0x107f4 - 0x10800
int32_t function_107f4(void) {
    // 0x107f4
    int32_t i_v1; // 0x107f4
    return i_v1;
}

// Address range: 0x10800 - 0x1080c
int32_t function_10800(void) {
    // 0x10800
    int32_t i_v1; // 0x10800
    return i_v1;
}

// Address range: 0x1080c - 0x10818
int32_t function_1080c(void) {
    // 0x1080c
    int32_t i_v1; // 0x1080c
    return i_v1;
}

// Address range: 0x10818 - 0x10824
int32_t function_10818(void) {
    // 0x10818
    int32_t i_v1; // 0x10818
    return i_v1;
}

// Address range: 0x10824 - 0x10830
int32_t function_10824(void) {
    // 0x10824
    int32_t i_v1; // 0x10824
    return i_v1;
}

// Address range: 0x10830 - 0x1083c
int32_t function_10830(void) {
    // 0x10830
    int32_t i_v1; // 0x10830
    return i_v1;
}

// Address range: 0x1083c - 0x10848
int32_t function_1083c(void) {
    // 0x1083c
    int32_t i_v1; // 0x1083c
    return i_v1;
}

// Address range: 0x10848 - 0x10854
int32_t function_10848(void) {
    // 0x10848
    int32_t i_v1; // 0x10848
    return i_v1;
}

// Address range: 0x10854 - 0x10860
int32_t function_10854(void) {
    // 0x10854
    int32_t i_v1; // 0x10854
    return i_v1;
}

// Address range: 0x10860 - 0x1086c
int32_t function_10860(void) {
    // 0x10860
    int32_t i_v1; // 0x10860
    return i_v1;
}

// Address range: 0x1086c - 0x10878
int32_t function_1086c(void) {
    // 0x1086c
    int32_t i_v1; // 0x1086c
    return i_v1;
}

// Address range: 0x10878 - 0x10884
int32_t function_10878(void) {
    // 0x10878
    int32_t i_v1; // 0x10878
    return i_v1;
}

// Address range: 0x10884 - 0x10890
int32_t function_10884(void) {
    // 0x10884
    int32_t i_v1; // 0x10884
    return i_v1;
}

// Address range: 0x10890 - 0x1089c
int32_t function_10890(void) {
    // 0x10890
    int32_t i_v1; // 0x10890
    return i_v1;
}

// Address range: 0x1089c - 0x108a8
int32_t function_1089c(void) {
    // 0x1089c
    int32_t i_v1; // 0x1089c
    return i_v1;
}

// Address range: 0x108a8 - 0x108b4
int32_t function_108a8(void) {
    // 0x108a8
    int32_t i_v1; // 0x108a8
    return i_v1;
}

// Address range: 0x108b4 - 0x108c0
int32_t function_108b4(void) {
    // 0x108b4
    int32_t i_v1; // 0x108b4
    return i_v1;
}

// Address range: 0x108c0 - 0x108cc
int32_t function_108c0(void) {
    // 0x108c0
    int32_t i_v1; // 0x108c0
    return i_v1;
}

// Address range: 0x108cc - 0x108d8
int32_t function_108cc(void) {
    // 0x108cc
    int32_t i_v1; // 0x108cc
    return i_v1;
}

// Address range: 0x108d8 - 0x108e4
int32_t function_108d8(void) {
    // 0x108d8
    int32_t i_v1; // 0x108d8
    return i_v1;
}

// Address range: 0x108e4 - 0x108f0
int32_t function_108e4(void) {
    // 0x108e4
    int32_t i_v1; // 0x108e4
    return i_v1;
}

// Address range: 0x108f0 - 0x108fc
int32_t function_108f0(void) {
    // 0x108f0
    int32_t i_v1; // 0x108f0
    return i_v1;
}

// Address range: 0x108fc - 0x10908
int32_t function_108fc(void) {
    // 0x108fc
    int32_t i_v1; // 0x108fc
    return i_v1;
}

// Address range: 0x10908 - 0x10914
int32_t function_10908(void) {
    // 0x10908
    int32_t i_v1; // 0x10908
    return i_v1;
}

// Address range: 0x10914 - 0x10920
int32_t function_10914(void) {
    // 0x10914
    int32_t i_v1; // 0x10914
    return i_v1;
}

// Address range: 0x10920 - 0x1092c
int32_t function_10920(void) {
    // 0x10920
    int32_t i_v1; // 0x10920
    return i_v1;
}

// Address range: 0x1092c - 0x10938
int32_t function_1092c(void) {
    // 0x1092c
    int32_t i_v1; // 0x1092c
    return i_v1;
}

// Address range: 0x10938 - 0x10b78
int32_t function_10938(int32_t i_a1, int32_t i_a2) {
    // 0x10938
    if (function_107c4() != 0) {
        // 0x10968
        return function_10ee0(*(int32_t *)(i_a2 + 4));
    }
    // 0x10970
    if (function_107c4() == 0) {
        // 0x10adc
        function_10824();
        // 0x10968
        return -1;
    }
    // 0x10988
    if (function_108d8() == -1) {
        // 0x10af0
        function_1092c();
    } else {
        // 0x109a4
        function_10884();
        function_108e4();
        function_10c5c("22322");
        function_107d0();
        if (function_10878() != -1) {
            // 0x10a08
            if (function_108c0() == -1) {
                // 0x10b34
                function_10800();
                function_10860();
                // 0x10b5c
                return function_1092c();
            }
            while (true) {
                // 0x10a24
                function_10824();
                if (function_107f4() == -1) {
                    // 0x10ac0
                    function_10800();
                } else {
                    // 0x10a54
                    function_10824();
                    if (function_10818() == -1) {
                        // break -> 0x10a80
                        break;
                    }
                }
            }
            // 0x10a80
            function_10800();
            if (function_108b4() == -1) {
                // 0x10b5c
                return function_1092c();
            }
            // 0x10aac
            function_10824();
            // 0x10968
            return 0;
        }
    }
    // 0x10b0c
    function_10800();
    function_10860();
    // 0x10b34
    function_10800();
    function_10860();
    // 0x10b5c
    return function_1092c();
}

// Address range: 0x10b7c - 0x10ba4
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10b7c
    function_10830();
    return function_108f0();
}

// Address range: 0x10bac - 0x10bc8
int32_t function_10bac(void) {
    // 0x10bac
    if (i_g2 == 0) {
        int32_t i_v1; // 0x10bac
        return i_v1;
    }
    // 0x10bc4
    return function_10848();
}

// Address range: 0x10bd0 - 0x10bee
int32_t function_10bd0(void) {
    // 0x10bd0
    return &i_g3;
}

// Address range: 0x10bf4 - 0x10c20
int32_t function_10bf4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10bf4
    int32_t i_v1; // 0x10bf4
    int32_t i_v2 = i_v1;
    bool i_v3; // 0x10bf4
    if (i_v3) {
        __asm_msreq(i_v1, 0x4100000);
        return i_a1;
    }
    bool i_v4; // 0x10bf4
    if (!i_v3) {
        int32_t i_v5 = (i_v2 << i_v1) + i_v2;       // 0x10c04
        int32_t i_v6 = i_v5 & -1 - 0x400000 * i_v5; // 0x10c08
        i_v4 = i_v6 < 0;
        if (i_v6 == 0) {
            return unknown_240((int32_t)&i_g5);
        }
    }
    // 0x10c18
    if (i_v4 != i_v3) {
        __asm_svclt(0x4770);
    }
    return i_a1;
}

// Address range: 0x10c20 - 0x10c38
int32_t function_10c20(void) {
    // 0x10c20
    int32_t i_v1; // 0x10c20
    if (*(char *)&p_g4 == 0) {
        int32_t i_v2 = function_10bd0(); // 0x10c2e
        *(char *)&p_g4 = 1;
        i_v1 = i_v2;
    }
    // 0x10c36
    return i_v1;
}

// Address range: 0x10c38 - 0x10c3c
int32_t function_10c38(int32_t i_a1, int32_t i_a2) {
    // 0x10c38
    return i_a1;
}

// Address range: 0x10c3e - 0x10c4a
int32_t function_10c3e(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10c3e
    bool i_v1; // 0x10c3e
    if (i_v1) {
        return i_a1;
    }
    int32_t i_v2 = i_a1; // 0x10c42
    int32_t i_v3;        // 0x10c3e
    int16_t i_v4 = i_v3; // 0x10c42
    if (i_v1) {
        *(int16_t *)i_v3 = i_v4;
    }
    return i_v2;
}

// Address range: 0x10c4a - 0x10c4c
int32_t function_10c4a(void) {
    // 0x10c4a
    int32_t i_v1; // 0x10c4a
    return function_10bf4(i_v1, i_v1, i_v1, i_v1);
}

// Address range: 0x10c4c - 0x10c58
int32_t function_10c4c(int32_t i_a1) {
    // 0x10c4c
    bool i_v1; // 0x10c4c
    if (i_v1) {
        return unknown_240(i_a1);
    }
    // 0x10c54
    return i_a1;
}

// Address range: 0x10c58 - 0x10c5c
int32_t function_10c58(void) {
    // 0x10c58
    int32_t i_v1; // 0x10c58
    return i_v1;
}

// Address range: 0x10c5c - 0x10cac
int32_t function_10c5c(char *p_a1) {
    int32_t i_v1 = (int32_t)p_a1;
    int32_t i_v2 = function_1086c(); // 0x10c64
    int32_t i_v3 = i_v1 - 1;
    int32_t i_v4 = i_v1 - 2 + i_v2; // 0x10c78
    int32_t i_v5 = 0;               // 0x10c98
    if (i_v3 == i_v4) {
        // 0x10c9c
        return (int32_t) * (char *)(i_v2 + i_v3) - 48;
    }
    int32_t i_v6 = i_v3; // 0x10c98
    i_v6++;
    i_v5 = 10 * (i_v5 - 48 + (int32_t) * (char *)i_v6);
    while (i_v6 != i_v4) {
        // 0x10c80
        i_v6++;
        i_v5 = 10 * (i_v5 - 48 + (int32_t) * (char *)i_v6);
    }
    // 0x10c9c
    return i_v5 - 48 + (int32_t) * (char *)(i_v2 + i_v3);
}

// Address range: 0x10cac - 0x10ee0
int32_t function_10cac(int32_t i_a1) {
    // 0x10cac
    function_10824();
    int32_t i_v1 = 0; // bp-2064, 0x10cd4
    function_10884();
    function_107dc();
    function_107d0();
    if (function_1089c() != 0) {
        // 0x10d74
        function_107d0();
        function_10908();
        function_108a8();
        char i_v2 = *(char *)1025; // 0x10d94
        if (i_v2 != 0) {
            char i_v3 = i_v2;    // 0x10d94
            int32_t i_v4 = 1025; // 0x10d94
            int32_t i_v5;        // 0x10cac
            uint32_t i_v6;       // 0x10d4c
            int32_t i_v7;        // 0x10d94
            int16_t i_v8;        // 0x10d30
            while (true) {
                // 0x10d2c
                i_v5 = i_v4;
                i_v7 = i_v3;
                i_v8 = *(int16_t *)(2 * i_v7 + (int32_t)&i_v1);
                if (i_v3 != 95 && (i_v8 & 8) == 0) {
                    // 0x10d4c
                    i_v6 = i_v7 - 45;
                    if (i_v6 != 2 && i_v6 >= 2) {
                        // break -> 0x10d58
                        break;
                    }
                }
                // 0x10d94
                i_v4 = i_v5 + 1;
                i_v3 = *(char *)i_v4;
                if (i_v3 == 0) {
                    // break (via goto) -> 0x10da0
                    goto lab_0x10da0;
                }
            }
            // 0x10d58
            function_10824();
            function_10908();
            function_108a8();
            function_107d0();
            function_10908();
            function_108a8();
            int32_t i_v9 = i_v5 + 1;    // 0x10d94
            char i_v10 = *(char *)i_v9; // 0x10d94
            while (i_v10 != 0) {
                // 0x10d2c
                i_v3 = i_v10;
                i_v4 = i_v9;
                while (true) {
                    // 0x10d2c
                    i_v5 = i_v4;
                    i_v7 = i_v3;
                    i_v8 = *(int16_t *)(2 * i_v7 + (int32_t)&i_v1);
                    if (i_v3 != 95 && (i_v8 & 8) == 0) {
                        // 0x10d4c
                        i_v6 = i_v7 - 45;
                        if (i_v6 != 2 && i_v6 >= 2) {
                            // break -> 0x10d58
                            break;
                        }
                    }
                    // 0x10d94
                    i_v4 = i_v5 + 1;
                    i_v3 = *(char *)i_v4;
                    if (i_v3 == 0) {
                        // break (via goto) -> 0x10da0
                        goto lab_0x10da0;
                    }
                }
                // 0x10d58
                function_10824();
                function_10908();
                function_108a8();
                function_107d0();
                function_10908();
                function_108a8();
                i_v9 = i_v5 + 1;
                i_v10 = *(char *)i_v9;
            }
        }
    }
lab_0x10da0:
    // 0x10da0
    function_10884();
    function_1080c();
    uint32_t i_v11 = function_1083c(); // 0x10e00
    if (i_v11 == -1) {
        // 0x10e74
        function_10824();
        goto lab_0x10e4c;
    } else {
        // 0x10e10
        function_107d0();
        int32_t i_v12 = __asm_ubfx(i_v11, 8, 8); // 0x10e24
        if (i_v11 % 128 == 0) {
            if (i_v12 == 0) {
                // 0x10e34
                function_10824();
            } else {
                // 0x10e90
                function_107d0();
                function_108cc();
            }
        } else {
            // 0x10eb8
            function_107d0();
            function_108cc();
        }
        goto lab_0x10e4c;
    }
lab_0x10e4c:
    // 0x10e4c
    function_1086c();
    function_10890();
    function_10908();
    function_108a8();
    // 0x10e74
    function_10824();
    goto lab_0x10e4c;
}

// Address range: 0x10ee0 - 0x11008
int32_t function_10ee0(int32_t i_a1) {
    // 0x10ee0
    if (i_a1 == 0) {
        // 0x10fc8
        return -3;
    }
    // 0x10ee8
    function_108e4();
    function_10c5c("22322");
    if (function_108d8() < 0) {
        // 0x10fd8
        function_107e8();
        // 0x10fc8
        return -1;
    }
    // 0x10f4c
    if (function_10920() < 0) {
        // 0x10fec
        function_107e8();
        // 0x10fc8
        return -2;
    }
    // 0x10f60
    function_1086c();
    function_10914();
    int32_t i_v1 = 0; // bp-1040, 0x10f88
    function_10884();
    uint32_t i_v2 = function_108fc(); // 0x10fa0
    int32_t i_v3 = -3;                // 0x10fa8
    if (i_v2 >= 1) {
        // 0x10fac
        int32_t i_v4; // bp-16, 0x10ee0
        *(char *)((int32_t)&i_v4 - 1024 + i_v2) = 0;
        int32_t i_v5 = function_10c5c((char *)&i_v1); // 0x10fbc
        i_v3 = i_v5 == 200 ? 0 : i_v5;
    }
    // 0x10fc8
    return i_v3;
}

// Address range: 0x11008 - 0x11040
int32_t function_11008(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_107a4(i_a1, i_a2, i_a3, i_a4); // 0x1101a
    return (int32_t)&i_g1 - 0x15790 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x1104c - 0x11054
int32_t function_1104c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x1104c
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 48
